### ISSUE TITLE
ohlcvs not increasing

### ISSUE THREAD

**Issue by CharlesFr** [ccxt-dev/ccxt#221]
I'm trying the retrieve the daily price for the past 5 days without much luck. Despite `from_timestamp` increasing appropriately `gdax.fetch_ohlcv('BTC/USD', '1d', from_timestamp)` returns the same value.

```
now = gdax.seconds()

from_datetime = '2017-09-14 00:00:00'

from_timestamp = iso8601_to_epoch(from_datetime)

day = 60 * 60 * 24

data = []


while from_timestamp < now:
    
    try:

        ohlcvs = gdax.fetch_ohlcv('BTC/USD', '1d', from_timestamp)
        
        from_timestamp += day
        
        print(from_timestamp, ohlcvs)

        data += ohlcvs
    
    except Exception as e:
        
        print(e)

print(len(data))
```

ps: I have also tried in milliseconds

**Comment by kroitor** [comment]
P.S. I also updated the [examples/py/fetch-ohlcv-sequentially](https://github.com/ccxt-dev/ccxt/blob/master/examples/py/fetch-ohlcv-sequentially.py) for demonstrating the fixed GDAX fetchOHLCV method.

**Comment by kroitor** [comment]
P.S. I also updated the [examples/py/fetch-ohlcv-sequentially](https://github.com/ccxt-dev/ccxt/blob/master/examples/py/fetch-ohlcv-sequentially.py) to demonstrate the fix.
