### ISSUE TITLE
Bitstamp fetchOrderStatus fill throw Exception

### ISSUE THREAD

**Issue by quorak** [ccxt-dev/ccxt#226]
In the v2 API of Bitstamp `fetchOrderStatus` you are referencing a not existing API definition `privatePostOrderStatus` .

In v1 `privatePostOrderStatus` is defined but not in v2. Maybe we just add it back.

**Comment by kroitor** [comment]
Thank you very much for reporting this! I restored the missing endpoint in Bitstamp v2, it should be working normally as of v1.7.111+ (will be downloadable in several minutes). Let us know if you have any difficulty with it.

**Comment by quorak** [comment]
I'm sorry. it seems like the order_status endpoint is not supported for v2. Not sure if it is a bug on bitstamp or intended. The requests returns a `POST Only Endpoint` response, even though you make a Post requests. going to the v1 API, it works as expected.

Check https://github.com/krystianity/node-bitstamp/blob/5a56f9cfacb2a820a71a5938a8ba03a79b89f5eb/lib/Bitstamp.js#L22 and  https://github.com/krystianity/node-bitstamp/blob/5a56f9cfacb2a820a71a5938a8ba03a79b89f5eb/lib/Bitstamp.js#L198 they also switch between the Versions. Very strange Endpoint.

**Comment by kroitor** [comment]
@quorak there was a missing slash in the endpoint, I reuploaded the fix for it, but I can't test it on my side, don't have a bitstamp verification to get a keypair, so we will be happy if you can download it (v.1.7.123+) and test it and then report back here. Thx! If it still does not work, I'll remove it from v2.

**Comment by quorak** [comment]
this works. thanks.

**Comment by kroitor** [comment]
@quorak thx for reporting back on this!
