### ISSUE TITLE
coincheck ETH/BTC orderbook not correct

### ISSUE THREAD

**Issue by 86chenjie** [ccxt-dev/ccxt#236]
should be around 0.07 from https://coincheck.com/exchange,
but return around 434k. guess it return BTC/JPY value.

**Comment by kroitor** [comment]
BTC/JPY is the only "real" trading pair on coincheck... I'll put an exception there.

**Comment by kroitor** [comment]
This will throw an exception as of v1.8.26+ if you're trying to fetch anything other than BTC/JPY from coincheck. Thx again!

**Comment by 86chenjie** [comment]
if coincheck only support BTC/JPY trading. i think it's better to only return BTC/JPY in loadMarkets  api.
how do you think?

**Comment by kroitor** [comment]
I think, you're right, actually. Will do that right away. They were off by default, I don't remember why I had to turn them on... I'll switch them back off.

**Comment by 86chenjie** [comment]
👍

**Comment by kroitor** [comment]
@86chenjie btw, I wanted to ask you... Being located in China you probably know more about internal affairs, what should we expect from local Chinese exchanges? Are they all going to cease their operations, or some of them will remain open and continue working out there? We've been testing Yunbi and their API is down for several days without a notice...

**Comment by 86chenjie** [comment]
@kroitor  
1. for cryptocurrency/CNY pairs
chinese government will stop all cryptocurrency/CNY pairs for all exchanges in china before 2017/10/31. 
2. for cryptocurrency/cryptocurrency pairs
many chinese exchanges already/plan to open international version exchanges for coin/coin trading pairs.

so ccxt should be prepared to add those international version exchanges.
btw, i also want to know whether ccxt has plan to add support for those decentralized exchanges like BTS ?

**Comment by kroitor** [comment]
@86chenjie thx for answering! We are going to be prepared )

> btw, i also want to know whether ccxt has plan to add support for those decentralized exchanges like BTS ?

We'd love to have support for p2p exchanges like BitShares and some others that we have in our lists! And we also want to incorporate smart contract trading! But our current topmost priority is implementing the portable WebSocket streaming APIs, and, btw, we are almost there ;)

**Comment by 86chenjie** [comment]
glad to hear that!  👍
