### ISSUE TITLE
how did fetch functions work in python version?

### ISSUE THREAD

**Issue by aobuke** [ccxt-dev/ccxt#237]
I am wondering how did functions like self.privatePostQueryOrders(), privatePostOpenOrders call the request()?

I have check all the codes but could not find the detailed call relationship or the definition of privatePostQueryOrders(). Thanks

**Comment by kroitor** [comment]
Hi! Take a look at the function 'define_rest_api' in exchange.py. Upon instantiation the exchange class takes each URL from its endpoint list, splits it into words, and then makes up a callable function name from those words by using a partial function. That process is the same in JS and PHP as well. It is described briefly here: https://github.com/ccxt-dev/ccxt/wiki/Manual#api-method-naming-conventions . If that answers your question, please, close this issue. We will be happy to answer all your further questions. Thx!
