### ISSUE TITLE
Cryptopia base and quote currency reversed

### ISSUE THREAD

**Issue by rdbr** [ccxt-dev/ccxt#239]
The symbols Cryptopia uses have a reversed base and quote currency: `DOT/BTC`

Here you can see the results of a `loadMarkets()`.
```
"DOT/BTC": {
    "id": 100,
    "symbol": "DOT/BTC",
    "base": "DOT",
    "quote": "BTC",
    "info": {
        "Id": 100,
        "Label": "DOT/BTC",
        "Currency": "Dotcoin",
        "Symbol": "DOT",
        "BaseCurrency": "Bitcoin",
        "BaseSymbol": "BTC",
        "Status": "OK",
        "StatusMessage": null,
        "TradeFee": 0.2,
        "MinimumTrade": 1e-8,
        "MaximumTrade": 100000000,
        "MinimumBaseTrade": 0.00005,
        "MaximumBaseTrade": 100000000,
        "MinimumPrice": 1e-8,
        "MaximumPrice": 100000000
    },
    "maker": 0.002,
    "taker": 0.002
},
```

`base` should be `BTC`.

The simple fix:
```
quote, base = symbol.split('/')
```

**Comment by kroitor** [comment]
Hi! Are you sure?

```Python
mbp:ccxt igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> ccxt.cryptopia().fetch_ticker('ETH/BTC')
{'info': {u'SellVolume': 188.35382172, u'Volume': 245.03618377, u'SellBaseVolume': 1749.11356114, u'LastPrice': 0.07432773, u'TradePairId': 5203, u'Label': u'ETH/BTC', u'High': 0.07739843, u'BidPrice': 0.07411123, u'Low': 0.07317848, u'BuyBaseVolume': 5.44148343, u'Close': 0.07432773, u'BaseVolume': 18.27058447, u'Open': 0.07527184, u'AskPrice': 0.07488253, u'Change': -1.25, u'BuyVolume': 206680.7995918}, 'last': 0.07432773, 'timestamp': 1506464237929, 'bid': 0.07411123, 'vwap': None, 'datetime': '2017-09-26T22:17:17.000Z', 'high': 0.07739843, 'low': 0.07317848, 'quoteVolume': 245.03618377, 'ask': 0.07488253, 'close': 0.07432773, 'percentage': None, 'baseVolume': 18.27058447, 'open': 0.07527184, 'average': None, 'change': -1.25, 'first': None}
>>> 
```

Looks like ETH/BTC is correct. ETH is the base. Price is ~ 0.07. So, BTC is quote. Or am I missing something?

**Comment by rdbr** [comment]
Check out the volumes in your example. `baseVolume` is in BTC.
```
'quoteVolume': 245.03618377,
'baseVolume': 18.27058447,
```

Here is the Cryptopia API GetMarkets:
```
GetMarkets
Returns all market data
GET https://www.cryptopia.co.nz/api/GetMarkets
Param: baseMarket (optional, default: All)
Param: hours (optional, default: 24)
```

If you get base BTC markets with `https://www.cryptopia.co.nz/api/GetMarkets/BTC` you will see the `ETH/BTC` pair.

**Comment by kroitor** [comment]
> Check out the volumes in your example. baseVolume is in BTC.

Yep, the volumes look misplaced, I agree here, and I'll fix the tickers for that. But the price is still correct, and the price is for ETH/BTC where ETH is base and BTC is quote.

> If you get base BTC markets with https://www.cryptopia.co.nz/api/GetMarkets/BTC you will see the ETH/BTC pair.

What I'm trying to explain to you, is that Cryptopia field naming is inconsistent, they call BTC "base", but it is a quote currency in fact. BTC is actually the quote currency in ETH/BTC pair. Take a look at the definition of base-quote (not the way Cryptopia named base and quote sides, but the way they really are named by the rest of the world).

You don't get base BTC markets with https://www.cryptopia.co.nz/api/GetMarkets/BTC, you are actually getting the "quote-BTC" markets this is clear if you compare their prices to all other exchanges. ETH/BTC is ~ 0.7, BCH/BTC is ~ 0.1, so this is called "BTC is quote", we pay or receive that quote BTC price for 1 lot of base altcoin. This is the correct terminology afaik.

So, the base-quote are in their proper places and only the ticker volumes should be corrected, right? Or am I wrong?

**Comment by kroitor** [comment]
Ok, I uploaded the fix for ticker volumes in Cryptopia. This should be working since 1.8.35+ (in a couple of minutes). 

Let us know if you still insist that base-quote sides are misplaced there and we are mistaking.

**Comment by rdbr** [comment]
Thanks for the fix!

I agree about the base-quote. The crypto market isn't always consistent with the real stock market.
As long as the unified API gives consistent results across the exchanges, I'm fine with that.

**Comment by kroitor** [comment]
@rdbr , ok ) Let us know if you find anything strange or suspicious (with other exchanges, maybe) your feedback is very helpful to us and other users! Thx again!

**Comment by rdbr** [comment]
The following exchanges have the same problem of reversing the base and quote volume: Poloniex, Bittrex
I didn't look at the other exchanges, but there are probably a lot more with this problem.

Fixes:

Poloniex
```
        'baseVolume': parseFloat (ticker['quoteVolume']),
        'quoteVolume': parseFloat (ticker['baseVolume']),
```

Bittrex
```
        'baseVolume': parseFloat (ticker['Volume']),
        'quoteVolume': parseFloat (ticker['BaseVolume']),
```

**Comment by kroitor** [comment]
@rdbr hm... but you agreed previously on the 'base-quote' ) They're not reversed actually, ccxt has them correct and consistent across Poloniex and Bittrex for sure.

**Comment by kroitor** [comment]
![details](https://user-images.githubusercontent.com/1294454/31219822-2a070cc2-a9c7-11e7-926b-b996011fa4c1.jpg)

**Comment by kroitor** [comment]
1 ETH / 1 BTC = 0.06950101, so the pair is ETH/BTC (we buy/sell ETH for a price in BTC). This is the price Bittrex shows. And it's for ETH/BTC.

1 BTC / 1 ETH ~ 14.38828011, so the pair is not BTC/ETH (we don't buy/sell BTC for ETH there). Bittrex shows you this name (BTC-ETH) for the market, while actually showing you the price for ETH/BTC at the same time. CCXT does that correctly, linking ETH/BTC name to Bittrex price.

**Comment by kroitor** [comment]
Let me know if everything is now clear to you on this issue. Thx!

**Comment by kroitor** [comment]
Oh, I'm sorry, I missed you were talking about the tickers. I'll reverse their volumes as well. Thx!

**Comment by kroitor** [comment]
Ok, I fixed the ticker volumes for both of them, it should be working in 1.9.29+ and a new fixed build will be available in several minutes. Thx for reporting on this! Really appreciate your involvement!

**Comment by rdbr** [comment]
Thanks!
