### ISSUE TITLE
Liqui cancel order

### ISSUE THREAD

**Issue by davidpodrebarac** [ccxt-dev/ccxt#241]
Hi,
using ccxt version 1.8.37., it looks like you have forgotten to await a coroutine for canceling orders in liqui class, line 13547.

```
    async def cancel_order(self, id):
        await self.load_markets()
        return self.privatePostCancelOrder({'order_id': id})
```

**Comment by kroitor** [comment]
Ooops, thx for pointing that out, fixing it right away!

**Comment by kroitor** [comment]
Yep, that comes from the differences in how JS and Python async functions work... This is fixed now, and it will be available in 1.8.38+ (in several minutes). Let us know if you find anything else missing. Feel free to reopen this issue if needed. Thx for your feedback!

**Comment by davidpodrebarac** [comment]
There seems to be a problem with more than one exchange. All of these are missing await in canceling orders:
bitfinex, bitstamp, bter, hitbtc, kraken, poloniex, yobit

**Comment by kroitor** [comment]
@davidpodrebarac this should now be fixed for all exchanges, thanks for reporting! Let us know if you have any other questions with it!
