### ISSUE TITLE
PHP Warning: fetch_order() compatibility with Exchange class

### ISSUE THREAD

**Issue by vondra** [ccxt-dev/ccxt#242]
PHP Warning:  Declaration of ccxt\binance::fetch_order($id, $symbol = NULL, $params = Array) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 2539
PHP Warning:  Declaration of ccxt\bitfinex::fetch_order($id, $params = Array) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 3453
PHP Warning:  Declaration of ccxt\bitstamp1::fetch_order($id) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 5621
PHP Warning:  Declaration of ccxt\bitstamp::fetch_order($id) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 5871
PHP Warning:  Declaration of ccxt\bittrex::fetch_order($id) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 6286
PHP Warning:  Declaration of ccxt\chbtc::fetch_order($id, $params = Array) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 9052
PHP Warning:  Declaration of ccxt\hitbtc::fetch_order($id, $params = Array) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 12819
PHP Warning:  Declaration of ccxt\hitbtc2::fetch_balance() should be compatible with ccxt\hitbtc::fetch_balance($params = Array) in /app/inc/ccxt.php on line 13087
PHP Warning:  Declaration of ccxt\kraken::fetch_order($id, $params = Array) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 14809
PHP Warning:  Declaration of ccxt\liqui::fetch_order($id, $symbol = NULL, $params = Array) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 15632
PHP Warning:  Declaration of ccxt\okcoin::fetch_order($id, $params = Array) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 16852
PHP Warning:  Declaration of ccxt\poloniex::fetch_order($id) should be compatible with ccxt\Exchange::fetch_order($id = NULL, $params = Array) in /app/inc/ccxt.php on line 17544

**Comment by kroitor** [comment]
Hi! Thanks for reporting! I'll fix these very soon.

**Comment by kroitor** [comment]
Ok, this is fixed. The working version is 1.8.41+ (will be available in a couple of minutes).

The proper signature of the unified fetchOrder method is like this:

```
fetchOrder(id, symbol = undefined, params = {}) // JavaScript
fetch_order(id, symbol=None, params={}) # Python
fetch_order($id, $symbol = null, $params = array ()) // PHP
```

Thx again for your feedback! Let us know if you have any remaining issues with this.
