### ISSUE TITLE
python: weird spacing for some if statements

### ISSUE THREAD

**Issue by thijstriemstra** [ccxt-dev/ccxt#244]
The generated Python sometimes contains:

```python
if(type == 'limit') or(type == 'market'):
```

where i'd expect:

```python
if (type == 'limit') or (type == 'market'):
```

See https://github.com/ccxt-dev/ccxt/blob/master/ccxt/exchanges.py#L2199 for example.

When this is fixed the flake8/pep8 rule for this should also be enabled (if possible).

**Comment by kroitor** [comment]
Thx for reporting this! I'll definitely fix for that. We'll need a separate transpiler rule for those clauses, no problem, will upload it fixed, asap! Thx again!

**Comment by kroitor** [comment]
Done! Thx again!

**Comment by kroitor** [comment]
@thijstriemstra I managed to satisfy all the flake8-ignored rules, and the only rule that's left is `E501 line too long (> 79 characters)`. I don't think this error is really critical, in fact, I think if I split those longer lines the code will bloat twice in size, so I'd rather leave the E501 ignore there.

**Comment by thijstriemstra** [comment]
Sounds good to me @kroitor!
