### ISSUE TITLE
TypeError: A Future, a coroutine or an awaitable is required

### ISSUE THREAD

**Issue by xgdgsc** [ccxt-dev/ccxt#247]
When running the example on async of python at https://github.com/ccxt-dev/ccxt/wiki/Manual#synchronous-vs-asynchronous-calls , I get this error:
```
Traceback (most recent call last):
  File "ccxt_logger.py", line 11, in <module>
    asyncio.get_event_loop().run_until_complete(print_bitfinex_ethbtc_ticker)
  File "anaconda3/lib/python3.6/asyncio/base_events.py", line 446, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "anaconda3/lib/python3.6/asyncio/tasks.py", line 520, in ensure_future
    raise TypeError('A Future, a coroutine or an awaitable is required')
TypeError: A Future, a coroutine or an awaitable is required
```

**Comment by kroitor** [comment]
Hi! Can you show your code? Because, afaik, there's no function print_bitfinex_ethbtc_ticker in that example, so we need to see how you defined it.

**Comment by xgdgsc** [comment]
Oh, actually the same code in wiki with poloniex doesn' t work with the same error message here.

**Comment by kroitor** [comment]
Also, it looks like you forgot the brackets in the coroutine, it should look like
```Python
# ...

asyncio.get_event_loop().run_until_complete(print_bitfinex_ethbtc_ticker()) # brackets here

# ...
```

**Comment by xgdgsc** [comment]
Thanks! Please update the wiki.

**Comment by kroitor** [comment]
Yep, there's a typo there. Updating it now! Thanks for opening this issue!
