### ISSUE TITLE
How can I use 'fetch_order_book' and pass optional params?

### ISSUE THREAD

**Issue by mellertson** [ccxt-dev/ccxt#250]
Thanks so much for publishing your library!  I've learned a lot by studying your code.  

I'm able to retrieve order book data from CEX with a code like so:

    import ccxt
    ex = CexExchange()
    results = ex.fetch_order_book(symbol='BTC/USD')

The results contain all of the order book ask and bid offers, works great.  But, I only want to fetch the first 10 asks and bids (i.e. depth = 10).  According to [CEX's api docs](https://cex.io/rest-api#orderbook), a url like the following does the trick:

[https://cex.io/api/order_book/BTC/USD/?depth=10](https://cex.io/api/order_book/BTC/USD/?depth=10)

Which raises the question, "How do I do this using the CCXT library?"  Having RTFM :blush:, it is my understanding the `params` argument can be used "to pass a custom setting or an optional parameter to your unified query." (ref: [https://github.com/ccxt-dev/ccxt/wiki/Manual#api-methods--endpoints](https://github.com/ccxt-dev/ccxt/wiki/Manual#api-methods--endpoints), end of sub-section Unified API).  I have tried the following code, but it raises an error:

    import ccxt
    ex = CexExchange()
    results = ex.fetch_order_book(symbol='BTC/USD', params={'depth': 10})

The exception raised is:

```
Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/home/mellertson/Documents/Development_Projects/Money_Maker/Python_Code/MoneyMaker/tests/Exchanges/test_Exchange_classes.py", line 668, in test_fetch_order_book____1_as_depth
    aResult = ex.fetch_order_book(symbol=iSymbol, params={'depth': 10})
  File "/home/mellertson/Documents/python_virtual_envs/python3.6/lib/python3.6/site-packages/ccxt/exchanges.py", line 7235, in fetch_order_book
    timestamp = orderbook['timestamp'] * 1000
KeyError: 'timestamp'
```

I also tried modifying `ccxt.cex.fetch_order_book` method, but to no avail.  I made the following modifications:

```
def fetch_order_book(self, symbol, params={}):
    self.load_markets()
    orderbook =  self.publicGetOrderBookPairDepth(self.extend({
        'pair': self.market_id(symbol),
    }, params))
    timestamp = orderbook['timestamp'] * 1000
    return self.parse_order_book(orderbook, timestamp)
```
And of modified the string in the params dictionary to read 'order_book/{pair}{depth}'.

Perhaps I am misunderstanding the docs. But, I'm at a loss for how to get this to work.  Any help would be greatly appreciated!

**Comment by mellertson** [comment]
I should also add, I looked through the examples you provided, but could not find an example of passing optional parameters to a REST api call.

**Comment by mellertson** [comment]
I'm guessing my taking the time to write up my question, perhaps it jogged my brain.  Because I found the problem.  There is a missing slash character at the end of the public GET api string in the `ccxt.cex` class on line 7208.  Once I appended the slash character, the following code works great:

```
import ccxt
ex = CexExchange()
results = ex.fetch_order_book(symbol='BTC/USD', params={'depth': 10})
```

**Comment by mellertson** [comment]
I ran all tests for the exchange "cex" before making any changes to the code.  I noted, there is a problem with the metod `ccxt.cex.fetch_balance`, but that seems unrelated to this issue.

I then made the fix, and ran tests for all languages, but again only for the exchange "cex".  All tests passed, except for the one noted above regarding `ccxt.cex.fetch_balance`.  It looks like the code fix worked, and didn't break anything.

**Comment by kroitor** [comment]
Hi, @mellertson ! Thank so much for your time fixing this! Really appreciate your involvement! I'll merge your PR right away! 

The fetch_balance test can fail because some user is using my testing keys for his own purposes and screws my nonce number all the time, so I refresh the testing keys from time to time. Apart from that everything looks very good. 

Also, note, that you don't have to edit all files for all languages, because our transpilation/build process takes source JS and puts all your changes into Py and PHP automatically, so, it's usually enough to edit the JS only, and the rest of the files are patched with Travis CI, here: https://travis-ci.org/ccxt-dev/ccxt/builds.

Thx again! Let us know you have any questions or difficulties with it.

**Comment by kroitor** [comment]
I also added examples on this to the Manual here: https://github.com/ccxt-dev/ccxt/wiki/Manual#order-book--market-depth

And uploaded the following examples into the repo:

- [examples/js/order-book-extra-level-depth-param.js](https://github.com/ccxt-dev/ccxt/blob/master/examples/js/order-book-extra-level-depth-param.js)
- [examples/py/order-book-extra-level-depth-param.py](https://github.com/ccxt-dev/ccxt/blob/master/examples/py/order-book-extra-level-depth-param.py)
- [examples/php/order-book-extra-level-depth-param.php](https://github.com/ccxt-dev/ccxt/blob/master/examples/php/order-book-extra-level-depth-param.php)

Thanks for pointing this out!
