### ISSUE TITLE
base/quote order

### ISSUE THREAD

**Issue by woudsma** [ccxt-dev/ccxt#252]
Hi, i'm not sure if this is a bug or a feature, but i hope someone can clarify this for me.
When using `exchange.loadMarkets()`, i see `base` / `quote` and `BaseCurrency` / `MarketCurrency`:
```
{ maker: 0.0025,
  taker: 0.0025,
  id: 'USDT-NEO',
  symbol: 'NEO/USDT',
  base: 'NEO',
  quote: 'USDT',
  info:
   { MarketCurrency: 'NEO',
     BaseCurrency: 'USDT',
     MarketCurrencyLong: 'Neo',
     BaseCurrencyLong: 'Tether',
     MinTradeSize: 1e-8,
     MarketName: 'USDT-NEO',
     IsActive: true,
     ...,
   }
}
```
These are reversed. My intuition says the base currency of a market e.g. `ETH/BTC` is `BTC` and market currency `ETH`. Or is this just a naming convention i'm unfamiliar with?

Side note: only Bittrex is working according to the docs for me atm, I've tried calling `loadMarkets` / `fetchBalance` / `fetchTicker(symbol)` on Poloniex/Bithumb/Bitfinex/Kraken (authenticed with API keys), but i'm getting a lot of errors, are these just development issues or should they work fine? I love the idea of a generic exchange API, but having to write a lot of exceptions when they might be fixed soon seems like a waste of time. Meanwhile i'm enjoying the API just fine ✨

**Comment by kroitor** [comment]
Hello, @woudsma !

For the first part of your question, the answer is thoroughly described in [the Manual](https://github.com/ccxt-dev/ccxt/wiki). I would recommend reading it very carefully letter by letter prior to coding. Most of non-obvious details are explained there. 

Namely: 
- the market structures are described here: https://github.com/ccxt-dev/ccxt/wiki/Manual#market-structure.
- ids and symbols are described here: https://github.com/ccxt-dev/ccxt/wiki/Manual#market-ids-and-symbols
- the naming consistency is described here: https://github.com/ccxt-dev/ccxt/wiki/Manual#naming-consistency

The `info` substructure is confusing you there, but you should not actually pay a lot of attention to it, if you're not extending the code. The `info` contains an original **unparsed** reply from the exchange. If you want to know real base and quote currencies, use the `base` and `quote` fields disregarding the contents of `info`.

Now depending on which exchange you are using, some of them have a reversed (inconsistent) pair naming, where they actually misplaced base and quote. For those the ccxt will do a correction, switching sides `base` and `quote` currencies when parsing exchange replies. This logic is financially and terminologically correct.

> These are reversed. My intuition says the base currency of a market e.g. ETH/BTC is BTC and market currency ETH. Or is this just a naming convention i'm unfamiliar with?

Your intuition is wrong. Base currency is always the one before the slash. And quote currency is always the one after the slash. For one unit of base currency we pay or receive a quoted price of another currency (quote currency). So, in ETH/BTC, ETH is base, BTC is quote. There's no such thing as "market currency" at all. Only "base" and "quote". This is consistent with the financial terminology adopted worldwide. For NEO/USDT from your example above, NEO is base, USDT is quote, which is true if you look at `base` and `quote` fields.

Standby, while I'm putting together a reply for your side note.

**Comment by woudsma** [comment]
@kroitor Thanks for the clarification, i'll dive into the docs again!
This should probably solve a few of my exchange errors as well, also i haven't spent that much time trying other exchanges yet.

**Comment by kroitor** [comment]
I don't know which language you are using, from your notation I suppose you're using JavaScript, so here's an example of how to fetch a ticker for Poloniex, Bithumb, Bitfinex and Kraken:

```JavaScript
"use strict";

const ccxt = require ('./ccxt')

async function test () {

    const ids = [ 'poloniex', 'bithumb', 'bitfinex', 'kraken' ]
    for (let i = 0; i < ids.length; i++) {
        const id = ids[i]
        const exchange = new ccxt[id] ({
            // connectivty errors, proxies and all that is also described in the manual
            'proxy': 'https://cors-anywhere.herokuapp.com/',
        })
        await exchange.loadMarkets ()

        // kraken has darkpool symbols and we don't want them here
        const filteredSymbols = exchange.symbols.filter (symbol => !exchange.markets[symbol]['darkpool'])

        let randomSymbol = filteredSymbols[Math.floor (Math.random () * exchange.symbols.length)]
        console.log (id, randomSymbol, await exchange.fetchTicker (randomSymbol))
    }
}

test ()
```

Let us know if this answers your question or not. If you have any difficulties with it, please, read more on troubleshooting here:
- [Troubleshooting](https://github.com/ccxt-dev/ccxt/wiki/Manual#troubleshooting)
- [Contributing issues](https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue)

Or if you have some specific question regarding the code, we will need to see your snippet to be able to help. In the meantime I'm closing this issue If you don't mind, feel free to reopen it, or just ask your further questions, we will be happy to answer.
