### ISSUE TITLE
proxy setting discuss

### ISSUE THREAD

**Issue by 86chenjie** [ccxt-dev/ccxt#259]
url = this.proxy + url

above is the code, so it will visit url like this: http://localhost:4042/api/proxy/test/http://api.chbtc.com/data/v1/depth?currency=eth_cny&size=3&merge=0.1

this don't follow url pattern. it 's hard to do url router map in nodejs expressjs.
expressjs seems not able to parse the original url correctly.
can we change it to like this:
http://localhost:4042/api/proxy/test?url=xxxxx
in which url is component encoded.

**Comment by xpl** [comment]
I think we should allow more flexible proxy pass configuration, maybe allowing to configure the `proxy` setting not just like this:

```javascript
    'proxy': 'https://crossorigin.me/', // string URL
```

...but in this way too (by allowing to pass a custom url mapping function):

```javascript
    'proxy': url => 'https://crossorigin.me/' + url
```

This will enable user to set his own proxy URL passing schema, for example:

```javascript
    'proxy': url => 'https://localhost:4042/?url=' + encodeURIComponent (url)
```

**Comment by 86chenjie** [comment]
yes. that would be better.

**Comment by 86chenjie** [comment]
btw, i think timeout probably should also be put into option

**Comment by kroitor** [comment]
@86chenjie which one? There is a timeout param already )

**Comment by 86chenjie** [comment]
@kroitor  
      const ex = new ccxt[exchange](options);
      ex.timeout = 2000; 

this is the way i use timeout.
setting timeout in options also work ?

**Comment by kroitor** [comment]
@86chenjie yep!) `new ccxt[exchange] ({ timeout: 2000 })`

**Comment by kroitor** [comment]
Ok, I added support for proxy url function overrides and uploaded a usage example here: https://github.com/ccxt-dev/ccxt/blob/master/examples/js/custom-proxy-url.js

Use it like this:

```JavaScript
"use strict";

const ccxt = require ('ccxt');

(async function main () {

    const kraken1 = new ccxt.kraken ({
        proxy: function (url) {
            return 'https://example.com/?url=' + encodeURIComponent (url)
        },
    })

    console.log (await kraken1.loadMarkets ())

    const kraken2 = new ccxt.kraken ({
        proxy: function (url) {
            return 'https://cors-anywhere.herokuapp.com/' + url
        },
    })

    console.log (await kraken2.loadMarkets ())

}) ()
```

Let us know if it doesn't work for you. I tested it locally, and it should work. Thx!

**Comment by kroitor** [comment]
A shorter version of it:

```Javascript
const kraken1 = new ccxt.kraken ({
    proxy: url => 'https://example.com/?url=' + encodeURIComponent (url),
})
```
