### ISSUE TITLE
Binance_limit_order_issue

### ISSUE THREAD

**Issue by rahulkumarbudhwani1** [ccxt-dev/ccxt#261]
While putting an order
binance.create_limit_buy_order('BNB/BTC',3,.000001)
I am getting the below error:
'quantity': ('{:.' + str(market['precision']['amount']) + 'f}').format(amount),
KeyError: 'precision'

**Comment by kroitor** [comment]
Hi! What's your version of ccxt?

**Comment by rahulkumarbudhwani1** [comment]
how can I check that?

**Comment by rahulkumarbudhwani1** [comment]
binance.version shows v1

**Comment by kroitor** [comment]
Type `pip list | grep ccxt`

**Comment by rahulkumarbudhwani1** [comment]
1.9.10

**Comment by kroitor** [comment]
Ok, thx, I'll fix it and get back to you soon.

**Comment by rahulkumarbudhwani1** [comment]
Ok I am going to sleep. Just let me know when you will be done with it.

**Comment by kroitor** [comment]
This will be fixed in 5 minutes. Please update to the most recent version of ccxt with `pip install ccxt -U` or `pip install ccxt --upgrade` and check if it's working for you. It should. Feel free to ask questions, if you have any difficulties with it. We will be thankful if you report back whether it works for you or not.

**Comment by rahulkumarbudhwani1** [comment]
It gives this error now

ccxt.errors.ExchangeNotAvailable: binance POST https://www.binance.com/api/v1/order 400 Bad Request  (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting, {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"})

**Comment by kroitor** [comment]
@rahulkumarbudhwani1 Now it's telling you to use a higher price and size, because each exchange has a minimal limit on volume, price and cost for any trade. Can you try a real price/volume?

**Comment by rahulkumarbudhwani1** [comment]
ok thanks

**Comment by rahulkumarbudhwani1** [comment]
exchange.fetchOrders (symbol = undefined, params = {})
I get an error that 'undefined' is not defined

**Comment by rahulkumarbudhwani1** [comment]
When I try to fetchOrder and store it in a variable and then when i print that variable then my  python stops responding.

**Comment by kroitor** [comment]
Can you post your code?

**Comment by rahulkumarbudhwani1** [comment]
a=binance.fetchOrders ('xxxxxxx')
print(a)
I think it is because the return array is too damn big
It gives array of 500 objects and each objects also contains multiple entries

**Comment by kroitor** [comment]
Nope, actually, their fetchOrders requires a symbol as well. Can you try it with `binance.fetchOrders ('xxxxxxx', 'BNB/BTC')` ?

**Comment by rahulkumarbudhwani1** [comment]
I tried this first 
binance.fetchOrder('xxxxxxx',symbol='BNB/BTC')
But now it worked after using it in above format

**Comment by kroitor** [comment]
Ok, thx for reporting back!
