### ISSUE TITLE
Binance Fetching Order or Cancelling order not working using 'id'

### ISSUE THREAD

**Issue by rahulkumarbudhwani1** [ccxt-dev/ccxt#265]
binance.cancel_order('7-dgit id',symbol='BNB/BTC')

This gives error as
ccxt.errors.ExchangeNotAvailable: binance DELETE https://www.binance.com/api/v1/order 400 Bad Request  (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting, {"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."})

**Comment by kroitor** [comment]
Hi! I uploaded a fix for it, thx for reporting on this! Please update to the new version of ccxt in 5 minutes and try the same code again. We will be happy if you report back, whether it worked for you or not.

**Comment by kroitor** [comment]
It is taking a little more time from Travis today, you can watch the build process here: 
https://travis-ci.org/ccxt-dev/ccxt/builds/282780887 when it finished with a green light, the fix will be available for updating.

**Comment by rahulkumarbudhwani1** [comment]
Hey, It hasn't uploaded till yet. Can you look open it?

**Comment by kroitor** [comment]
Yep, travis is experiencing a problem. We'll have to wait a little until they breathe again. I'm sorry for the inconvenience, but now it pretty much depends on their speed. It usually passed within 5 minutes, but as you can see, it can sometimes take longer. Please, be patient, it will hopefully be available soon.

**Comment by rahulkumarbudhwani1** [comment]
Ok no problem 
And once again thanks for listening to the bugs and helping out.

**Comment by kroitor** [comment]
@rahulkumarbudhwani1 ok, the build is done, please update to version 1.9.21+ and report if it's ok or not. Thx!

**Comment by rahulkumarbudhwani1** [comment]
Hey But it doesn't seem to be working. 
Can you tell me the format in which I should execute the cancel order command? Just confirming it

**Comment by rahulkumarbudhwani1** [comment]
Ok It is working
Once again thanks

**Comment by kroitor** [comment]
It should be like this:

```Python
binance.cancel_order('7-dgit id','BNB/BTC')
```

**Comment by kroitor** [comment]
Ok, thx for reporting! We really appreciate your feedback!

**Comment by rahulkumarbudhwani1** [comment]
Hey I need MACD data from binance site?
Is there anyway possible to include this in library?

**Comment by kroitor** [comment]
@rahulkumarbudhwani1 hi! Binance exchange does not offer MACD indications with their API. And you have to specify what kind of MACD over which variable you want. If you need to build a moving average crossover over the price you'll have to fetch their ticker data (you can do that with ccxt, like shown in the examples folder) and then calculate the indicator values over that data on your own. Also, there's a lot of statistical libraries that can help you do that once you collect the source data.

**Comment by rahulkumarbudhwani1** [comment]
I am kinda new to this. I studied that MACD is difference between 26 and 12 day moving average but I am confused whether the data I am seeing on the binance is exactly that MACD. I think it is different MACD

**Comment by rahulkumarbudhwani1** [comment]
![image](https://user-images.githubusercontent.com/32469024/31179677-3189d110-a93a-11e7-8c4d-35fa689b7f29.png)
I need the data in red line.

**Comment by kroitor** [comment]
Well, if you want to verify it, you will need to fetch OHLCVs or ticker data and check that mathematically. For fetching the data, you can use ccxt. And for calculating over it – you can use any statistical library of your choice that can calculate MACD for you.

**Comment by rahulkumarbudhwani1** [comment]
Ok let me try. Thanks for helping out

**Comment by kroitor** [comment]
Well, if you want to verify it, you will need to fetch OHLCVs or ticker data and check that mathematically. For fetching the data, you can use ccxt. And for calculating over it – you can use any statistical library of your choice that can find the MACD current values for you. 

Do you know how to calculate a moving average over some period? If not, I'd recommend to start from there. And if you do, then it should not really be a problem to subtract a higher timeframe from the lower timeframe or vice versa to get the value you want and check it. Cheers!

**Comment by kroitor** [comment]
@AlexGitRod you should post your code snippet and verbose output according to these instructions: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
