### ISSUE TITLE
Wallet Withdrawal, payment_method_id required on gdax?

### ISSUE THREAD

**Issue by PhinixPhire** [ccxt-dev/ccxt#266]
So it seems gdax requires a payment_method_id for withdrawal to another wallet. I, for the life of me, can't find where I should look for this id. I found this function:

getPayMentMethods()

...and wrote this quickie to see what's inside: 

for x in gdax.getPaymentMethods():
    print x
    for y in x:
        print '    ' + y

None of the IDs in the output work for the wallet withdrawal. I get an error like this:

Traceback (most recent call last):
  File "C:\Users\Kenneth\eclipse-workspace\Chank\CCXTtests.py", line 53, in <module>
    print gdax.withdraw('BTC', 0.01, '[BTC Wallet on another Exchange', params={'payment_method_id' : ''})
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 10921, in withdraw
    response = self.privatePostWithdraw(self.extend({
AttributeError: 'gdax' object has no attribute 'privatePostWithdraw'

This occurs regardless of what I assign to payment_method_id param. 

Is this an issue with CCXT, or an ID10T Error on my part?

**Comment by kroitor** [comment]
Hi! Thanks for your feedback. Just a sec, I'll check for that.

**Comment by kroitor** [comment]
Ok, I fixed this in ccxt and I uploaded the fix, please wait until the build finishes in approx 4-5 minutes (you can watch it here: https://travis-ci.org/ccxt-dev/ccxt/builds), then update to version 1.9.27+ and try again. It should work without the payment_method_id parameter (not required anymore if you withdraw BTC). Please let us know if it helps you or not. Thx!

**Comment by PhinixPhire** [comment]
That's wonderful, Igor!

Do you have a BTC or ETH address I can contribute just a little bit of
Thanks to?

I really appreciate your quick resolution and will let you know if it's
successful from my end.

Thanks and Best Regards,

Ken

**Comment by kroitor** [comment]
@PhinixPhire thx for your offer, Ken! ) We'd really appreciate a small tip, though, I suggest, let's see it working first, and then, if you report that everything is ok, I'll post my address here ) And if not, I'd like to fix it first. That'd be fair )

**Comment by kroitor** [comment]
Alright, the build is there, and the syntax is: 
```Python
gdax.withdraw('BTC', 0.01, 'address83948329473928') # should work
```

Standing by for your confirmation.

**Comment by PhinixPhire** [comment]
It works perfectly, Igor! Thanks again for your efforts. Please let me know
where I can contribute a small tip.

Much appreciated,

Ken

**Comment by kroitor** [comment]
@PhinixPhire thx for your involvement! My address is 3NnYkvDBNDFJf2cZPwiuGuW5Q4FM8Ys6CD.  Let us know if you have any other difficulties with, hope to help asap. Cheers!

**Comment by PhinixPhire** [comment]
No problem! It's been a pleasure.

That's a BTC address, then?
Sorry, want to be clear since I mentioned either BTC and ETH and I wouldn't
want the tip to get lost in space.

Have a great night!

Ken

**Comment by kroitor** [comment]
@PhinixPhire yep, it's BTC. Thx again!

**Comment by kroitor** [comment]
@PhinixPhire it has arrived, thx for your support!

**Comment by PhinixPhire** [comment]
Excellent. I also just saw the transaction complete. Happy to contribute!
In fact, I hope to contribute in other manners too in the near future.
You've got a great project going and I hope to be a part of it!
