### ISSUE TITLE
HitBTC create_order() fails in PHP

### ISSUE THREAD

**Issue by multipooleu** [ccxt-dev/ccxt#267]
I have define this var:

$exchange['hitbtc'] = new \ccxt\hitbtc(['apiKey' => 'xxx','secret' => 'yyy']);

And when i use:

$exchange['hitbtc']->fetch_balance();

It work fine, so api and secret are right.. but when i do:

print_r($exchange['hitbtc']->create_market_sell_order('LTC/BTC', 0.1));

Crash!

```
PHP Fatal error:  Uncaught ccxt\ExchangeNotAvailable: hitbtc POST http://api.hitbtc.com/api/1/trading/new_order?nonce=1507106702&apikey=xxx&clientOrderId=1507106702852&symbol=LTCBTC&side=sell&quantity=1&type=market not accessible from this location at the moment (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting in effect) in /source/temp/test_auto/ccxt.php:611
Stack trace:
#0 /source/temp/test_auto/ccxt.php(781): ccxt\Exchange->raise_error('ExchangeNotAvai...', 'http://api.hitb...', 'POST', 'not accessible ...', '(possible reaso...')
#1 /source/temp/test_auto/ccxt.php(632): ccxt\Exchange->fetch('http://api.hitb...', 'POST', Array, 'nonce=150710670...')
#2 /source/temp/test_auto/ccxt.php(13290): ccxt\Exchange->fetch2('new_order', 'trading', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\hitbtc->request('new_order', 'trading', 'POST', Array)
#4 /source/temp/test_auto/ccxt.php(575): call_user_func(Array, 'new_ord in /source/temp/test_auto/ccxt.php on line 611
```

**Comment by kroitor** [comment]
Hi! Thanks for reporting this! I'll check it asap and get back to you!

**Comment by kroitor** [comment]
Can you please check if your keys have the necessary permissions?
![screen shot 2017-10-05 at 01 52 06](https://user-images.githubusercontent.com/1294454/31203460-d2ea4082-a96f-11e7-9d96-28eac9a16595.png)

**Comment by multipooleu** [comment]
I haven't withdrawal because i don't need It:
[
![screenshot_20171005-081417](https://user-images.githubusercontent.com/7004721/31213158-4cf03ba4-a9a5-11e7-85ea-7fed80e0e40d.png)
](url)

**Comment by kroitor** [comment]
Ok, I'll debug it further and get back to you with a fix asap. Thx!

**Comment by kroitor** [comment]
Ok, I've been able to reproduce it, and I fixed this in version 1.9.33+. So, create_xxx_order should work with HitBTC in PHP now. Thanks for reporting this! Please update ccxt to the most recent version, the build should be available in about 5 minutes, then try it with the same code. I tested it locally and it now works for me. We will be thankful, if you tell us whether it works for you or not. Thx!

**Comment by kroitor** [comment]
Ok, the build is there and it should work normally, as expected. Waiting to hear from you.

**Comment by kroitor** [comment]
@multipooleu thx for reporting back! Let us know if you have any other questions. Cheers!
