### ISSUE TITLE
Backtesting

### ISSUE THREAD

**Issue by noahka** [ccxt-dev/ccxt#268]
I'm just wondering if its possible to use this platform to test hypothetical strategies, live and through backtesting. It would be useful to be able to assess strategies before implementing them. 

Thanks

**Comment by werewere** [comment]
To implement strategies, I suggest to @noahka to use pandas and ta-lib. Both are very useful.

**Comment by kroitor** [comment]
Also: https://community.backtrader.com/topic/623/anyone-use-backtrader-to-do-live-trading-on-bitcoin-exchange/14

> A feature-rich Python framework for backtesting and trading

https://www.backtrader.com/

**Comment by goushijie** [comment]
++1
