### ISSUE TITLE
Bittrex fetchOrders not showing all orders 

### ISSUE THREAD

**Issue by koubeissy-ibrahim** [ccxt-dev/ccxt#269]
Hello, 

i'm trying to use fetchOrders, i get few orders but not all orders, i'm connecting to my own account and there's some coins that i don't get orders for them, i'm using bittrex, i suspect that there's a limit on the dates cz all the orders that i don't receive date for more than two month does this make sense or not, 

also i'm trying to call fetchOrder('XRP/BTC') but i get a 403 is there anything wrong with my syntax ? 

thanks in advance and thanks for the great work

**Comment by kroitor** [comment]
@koubeissy-ibrahim Hello! Good to hear again from you!

> i'm trying to use fetchOrders, i get few orders but not all orders, i'm connecting to my own account and there's some coins that i don't get orders for them, i'm using bittrex, i suspect that there's a limit on the dates cz all the orders that i don't receive date for more than two month does this make sense or not,

Can you please show your code? Append backticks to format it when posting code, for more readability.

> also i'm trying to call fetchOrder('XRP/BTC') but i get a 403 is there anything wrong with my syntax ?

Looks like it is, fetchOrder is for fetching a single order by order id, not by a symbol. So the first argument should be a string literal order id, like so:
```
exchange.fetchOrder ('your_bittrex_order_id')
```

**Comment by kroitor** [comment]
I'm closing this issue for now, if you don't mind, until it has further story development. Feel free to reopen it if you still have any difficulties or questions with the library. Thx again!
