### ISSUE TITLE
Bitstamp missing bitcoin withdrawal method

### ISSUE THREAD

**Issue by davidpodrebarac** [ccxt-dev/ccxt#272]
Using ```ccxt==1.9.41```. 

I can't seem to find private api endpoints for withdrawing bitcoin on bitstamp v2. Comparing it to version 1, these methods are missing:
```
https://www.bitstamp.net/api/bitcoin_deposit_address/
https://www.bitstamp.net/api/unconfirmed_btc/
https://www.bitstamp.net/api/bitcoin_withdrawal/
```

**Comment by kroitor** [comment]
Hi, I added those missing endpoints, thank you very much for pointing that out! They should be available as of version 1.9.42+ in 5 minutes. Let us know if you have any difficulties with them. Cheers!

**Comment by davidpodrebarac** [comment]
I am also having problems fetching ltc address in python asyncio for bitstamp.

```
bitstamp = ccxt.bitstamp({
    "apiKey": "my_api_key",
    "secret": "my_secret",
    "uid" : "my_uid"

})
loop.run_until_complete(bitstamp.private_post_ltc_address())
```
It returns 400 error code:
```ExchangeNotAvailable: bitstamp POST https://www.bitstamp.net/api/v2/ltc_address 400```

**Comment by kroitor** [comment]
@davidpodrebarac and the others are working?

**Comment by davidpodrebarac** [comment]
Sorry, I haven't had the time to check it yesterday, but it seems to be working now. Thanks :slightly_smiling_face:

**Comment by kroitor** [comment]
@davidpodrebarac awesome! ) Good to know that! Thx, really appreciate your report!

**Comment by davidpodrebarac** [comment]
Hey, me again :) Using `ccxt async 1.9.71`

Wondering if this code works on your side:

```
bitstamp_ccxt = ccxt.bitstamp({
    "apiKey": "<<api_key>>",
    "secret": "<<secret>>
    "uid" : "<<uid>>"

})
loop.run_until_complete(bitstamp_ccxt.private_post_bitcoin_deposit_address())
```

I get a response containing a bunch of html code. Methods for xrp, eth and ltc work like a charm. 
Thanks!

**Comment by kroitor** [comment]
Can you post verbose output of it?

```
bitstamp_ccxt = ccxt.bitstamp({
    "apiKey": "<<api_key>>",
    "secret": "<<secret>>",
    "uid" : "<<uid>>",
    "verbose": True,
})
loop.run_until_complete(bitstamp_ccxt.private_post_bitcoin_deposit_address())
```

?

**Comment by kroitor** [comment]
Nope, never mind. The reason is: you should use bitstamp1 (v1) for BTC deposit and withdrawal. Looks like their v2 does not support that. I'll remove those endpoints.

**Comment by kroitor** [comment]
Actually, I think I'll add them to v2 but they will call v1 under the hood. Just to make it more convenient to those who want v2.

**Comment by davidpodrebarac** [comment]
Great, thank you! That is just what I wanted to ask you.

**Comment by kroitor** [comment]
Ok, I added them properly now, but because those methods use v1-endpoints inside, you should call them like so:

```
loop.run_until_complete(bitstamp_ccxt.v1_post_bitcoin_deposit_address()) # "private_" → "v1_"
```

Please update to version 1.9.91+ and try the above ↑ example now ) 
Let us know if it helped you or not.
Thx!

**Comment by davidpodrebarac** [comment]
It works great now.
