### ISSUE TITLE
problem in Poloniex

### ISSUE THREAD

**Issue by werewere** [ccxt-dev/ccxt#274]
Hi, first of all, amazing project, thanks :)

It seems that Poloniex is failing somehow, I wrote the following supersimple code:

```
import ccxt
polo   = ccxt.poloniex({
    'apiKey': 'MYKEY',
    'secret': 'MYSECRET',
})
print(polo.fetch_balance())
```

And it gives this error:

```
$ python bot.py 
Traceback (most recent call last):
  File "bot.py", line 36, in <module>
    print(polo.fetch_balance())
  File "/Library/Python/2.7/site-packages/ccxt/exchanges.py", line 15845, in fetch_balance
    'account': 'all',
  File "/Library/Python/2.7/site-packages/ccxt/exchanges.py", line 16134, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 228, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 266, in fetch
    self.handle_rest_errors(e, e.code, text, url, method)
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 314, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else str(http_status_code), details)
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 213, in raise_error
    details,
ccxt.errors.ExchangeNotAvailable: poloniex POST https://poloniex.com/tradingApi 422   {"error":"Nonce must be greater than 150619298582500. You provided 1507295961."}
```
It is working correctly with other exchanges, so I guess my setup is correct.

**Comment by kroitor** [comment]
Hi! Thanks for your feedback!

Can you create a new keypair and try again? Your keys seem to have been used in other software with milliseconds nonce. 

Read more about it here:

https://github.com/kroitor/ccxt/wiki/Manual#authentication
https://github.com/kroitor/ccxt/wiki/Manual#overriding-the-nonce
https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

If you cannot create a new keypair, then you can redefine your nonce to use milliseconds or even microseconds.

I actually recommend to read entire Manual: https://github.com/kroitor/ccxt/wiki/Manual it's all there. If you don't mind, i'm closing this as duplicate. Feel free to reopen it or just ask your questions, we will be happy to answer! Thx!

**Comment by werewere** [comment]
Ok, thanks for your help, is solved now :)

**Comment by kroitor** [comment]
@werewere thank you for reporting! Let us know if you have any other questions or difficulties. Cheers!

**Comment by nerdDan** [comment]
I am having the same error stack.

I guess it is because I am running two python script `fetch_orderbook_and_balance.py` and `place_order.py`, and two scripts create their own `ccxt.async` objects with same api keys.

I tried write exchange objects into shared memory so two scripts could share exchange objects, but failed.

Maybe I am not supposed to ask here, but I can't solve this on my own.

**Comment by kroitor** [comment]
> I guess it is because I am running two python scripts fetch_orderbook_and_balance.py and place_order.py, and two scripts create their own ccxt.async objects with same api keys.

It is exactly because of that. You can't use the same key within two processes that don't communicate, they have to share their nonce among them, and for that you will need to set up a common nonce source for both of your processes that would help eliminate the conflicts (well, mostly).

**Comment by nerdDan** [comment]
@kroitor thank you for replying! I found another solution: put all coroutines into one single thread.

May I ask another question? I only create one event loop in one thread. Why do I see multiple process with different pids?
