### ISSUE TITLE
bitfinex fetch_balance error params error and exchange verbose error

### ISSUE THREAD

**Issue by lidancheng** [ccxt-dev/ccxt#276]
hi, thanks for your best project!
I updated to tags/1.9.42, run on ubuntu python3.5 env.
I encounter two errors:
1. for exchange bitfinex, call the fetch_balance function got the following error:
`fetch_balance() takes 1 positional argument but 2 were given`
2. I create the exchange with verbose True options, I got the following error:
`'HTTPMessage' object has no attribute 'headers'`

best regards

**Comment by kroitor** [comment]
Hi! Thx for your feedback! Can you show a minimal snippet of code, please? (use formatting for readability). Thx!

**Comment by kroitor** [comment]
I fixed this, please update to version 1.9.44+ and try again, the fetch_balance should now work normally with Bitfinex in Python3! We will be thankful if you report back, whether it works for you or not. Cheers!

**Comment by lidancheng** [comment]
yeah! it's fixed.
thanks for your work

**Comment by kroitor** [comment]
@lidancheng thanks for reporting!
