### ISSUE TITLE
cancel_order(id)  for  CEX 

### ISSUE THREAD

**Issue by evgen-y2k** [ccxt-dev/ccxt#277]
cancel_order(id)  for  CEX  work but return error.

Traceback (most recent call last):
  File "/home/jo/trading/bot/ccxt_bot.py", line 162, in <module>
    print(cancel_order('4580833882'))
  File "/home/jo/trading/bot/ccxt_bot.py", line 64, in cancel_order
    res = cex.cancel_order(id)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/exchanges.py", line 7743, in cancel_order
    return self.privatePostCancelOrder({'id': id})
  File "/usr/local/lib/python2.7/dist-packages/ccxt/exchanges.py", line 7769, in request
    if 'e' in response:
TypeError: argument of type 'bool' is not iterable

**Comment by kroitor** [comment]
Thx for reporting this, will fix very soon!

**Comment by evgen-y2k** [comment]
OK. Will wait

**Comment by kroitor** [comment]
Ok, it should be fixed in the upcoming version 1.9.48+, please update in approx 5 minutes and try again. As always, we will be thankful if you report back! Thx!

**Comment by kroitor** [comment]
It's there, thx again!

**Comment by twmeggs** [comment]
* OS: Windows
* Programming Language version: Python 3.7.2 under Anaconda
* CCXT version: 1.18.198
* Exchange: CEX.IO
* Method: cancel_order(id)

Upon a successful single order cancellation, the CEX API returns a string of "true", as per the docs here: [https://cex.io/rest-api#cancel-order](url)

This value is check as a bool by ccxt and throws an ExchangeError, as per this:

```
C:\ProgramData\Anaconda3\envs\crypto\lib\site-packages\ccxt\async_support\cex.py in cancel_order(self, id, symbol, params)
    342     async def cancel_order(self, id, symbol=None, params={}):
    343         await self.load_markets()
--> 344         return await self.privatePostCancelOrder({'id': id})
    345
    346     def parse_order(self, order, market=None):

C:\ProgramData\Anaconda3\envs\crypto\lib\site-packages\ccxt\async_support\cex.py in request(self, path, api, method, params, headers, body)
    494                 if response['ok'] == 'ok':
    495                     return response
--> 496             raise ExchangeError(self.id + ' ' + self.json(response))
    497         elif 'error' in response:
    498             if response['error']:

ExchangeError: cex "true"
```

Should a workaround be put into the ccxt code base, or should I raise this with the CEX.IO team as a request to return a valid ```True``` boolean?

**Comment by runvnc** [comment]
I'm testing with Node.js 11.10.1, Linux, ccxt version 1.18.344 and getting

> TypeError: Cannot use 'in' operator to search for 'e' in true
>     at cex.request (/home/runvnc/coinado/node_modules/ccxt/js/cex.js:523:24)
>     at processTicksAndRejections (internal/process/next_tick.js:81:5)

It used to be (supposedly fixed?) with `if (response == true)`, which `'true' != true` (at least not in Node 9 or 11) so I'm not sure how that could have worked.  Then someone ran an eslint and now it says `if (response === true)` and that definitely doesn't work.
