### ISSUE TITLE
YoBit pair names

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#287]
CC (CoolinDarkCoin) Cryptopia in YoBit exchange is CCX, not CC
PAY (TenX) Cryptopia not PAY (Epay) YoBit
OMG (OmiseGo) Cryptopia not OMG (OMGame) YoBit
REP (Augur) Cryptopia not REP (RepubliCoin) Yobit
NAV (NAVcoin) Cryptopia not NAV (NavajoCoin) YoBit
LIZI (LiziCoin) Cryptopia not LIZI (LiZi) YoBit

**Comment by kroitor** [comment]
@mazertwo, CC is CyberCoin on CoinMarketCap. So, which one is true?

**Comment by mazertwo** [comment]
Cryptopia's CC is CoolinDarkCoin. 
YoBit CC is CyberCoin. 
Cryptopia's CC is Yobit CCX.

**Comment by kroitor** [comment]
@mazertwo yes, but CC means a third different currency named CC on CoinMarketCap, so which of them should be the actual CC currency:
- CoolinDarkCoin ?
- CyberCoin ?

**Comment by mazertwo** [comment]
I think, CC is CyberCoin, as coinmarketcap say :)

YoBit CCX = Cryptopia CC

**Comment by kroitor** [comment]
But if CC on Cryptopia is CoolinDarkCoin, then this contradicts CMC's CC for CyberCoin, doesn't it?

**Comment by kroitor** [comment]
Let me explain: we have support for 88 exchanges and crypto APIs including CoinMarketCap, so, we are really talking not about Cryptopia vs YoBit, but about the true pair namings for cryptocurrencies and their symbols. So, the actual questions is: which one is true CC?

**Comment by mazertwo** [comment]
I cant find CyberCoin on Cryptopia. Just only CoolinDarkCoin as CC name.

**Comment by kroitor** [comment]
@mazertwo if CC should mean CyberCoin as per CoinMarketCap (not Cryptopia), then what name should it be for Cryptopia ? CDC = CoolinDarkCoin? And vice versa, if we set CC = Cryptopia's CoolinDarkCoin, then we need to rename CyberCoin on Coinmarketcap ? For what? CBC ?

**Comment by mazertwo** [comment]
Ahaha, i think we just need remove CC from all pairs from Cryptopia in ccxt.
Or take YoBit name CCX for Cryptopia CC

**Comment by kroitor** [comment]
@mazertwo ok, so Cryptopia CC should be renamed to CCX to resolve the conflict... Yes, I agree on that. I'll fix it for Cryptopia and I'll dig into other pairs now, thx!

**Comment by mazertwo** [comment]
Thanks for you!

**Comment by kroitor** [comment]
@mazertwo looks like LIZI is the same as LiziCoin on Yobit? Can't find LiZi anywhere at all... Can you elaborate on this plz?

<img width="821" alt="screen shot 2017-10-07 at 17 31 16" src="https://user-images.githubusercontent.com/1294454/31308795-80061d4c-ab85-11e7-909d-29d3c30c6929.png">

**Comment by kroitor** [comment]
<img width="1120" alt="screen shot 2017-10-07 at 17 33 55" src="https://user-images.githubusercontent.com/1294454/31308820-bb113bce-ab85-11e7-8e22-33a8be4b8d4d.png">

**Comment by kroitor** [comment]
Most of them are fixed now, and the only one remaining is LIZI. Not sure if I should rename it on YoBit, because, it looks like LIZI first started trading there. Any ideas?

**Comment by mazertwo** [comment]
LiZi at YoBit looks like fake. You can't deposit and withdraw it. 
Lizi at YoBit cost 0.0001264 BTC
Lizi at Cryptopia cost 0.0000319 BTC
More than 3 times lower :)))

**Comment by kroitor** [comment]
@mazertwo but, actually, this can be the reverse – because it seems that LIZI first started on YoBit, and Cryptopia/Nova are both wrong ? Anyway, which one should we rename to what, how do you think?

**Comment by kroitor** [comment]
@yobit: LIZI → LiZi ?
or 
@cryptopia LIZI → LiZi + @nova LIZI → LiZi ?

**Comment by kroitor** [comment]
Ok, all pairs are renamed and are now closer to being consistent. Looks like we killed all the above bugs with your help! Let us know if you find any more. Thx!

![have a nice day](https://user-images.githubusercontent.com/1294454/31309110-ac5965f8-ab89-11e7-8054-bd481f7de8b2.gif)
