### ISSUE TITLE
Json.Parse Telegram getUpdate

### ISSUE THREAD

**Issue by BlackZero969** [ccxt-dev/ccxt#289]
I haven't parsed in Json. need to parse following. Apps-script code will be highly appreciated.

https://api.telegram.org/bot462465654:AAGVcamJZhXjlwCe2R3qAGHsMXTcNtY2hGY/getupdates

**Comment by kroitor** [comment]
@BlackZero969 you probably posted in wrong repo ) Sorry, I'm closing this.
