### ISSUE TITLE
Question about updating ticker

### ISSUE THREAD

**Issue by noahka** [ccxt-dev/ccxt#291]
I've gone through the manual and am playing around with things to make sure I know how they work.
I'm trying to get my program to print the newest version of the ticker every 2 seconds like this, and get this result:
![image](https://user-images.githubusercontent.com/32504129/31324129-286f807e-acfb-11e7-824b-2b8cd0a13933.png)
Can you help me with this? Sorry if its a noob question, like I said earlier I am still a student. 
Thanks

**Comment by kroitor** [comment]
@noahka hi!

The answer is:
1. Next time use GitHub Markdown to paste code in issues - it's much more convenient in text than on images. ;)
2. There's no such symbol as `['LTC/BTC']` ← you used square brackets and a `for` loop construct to iterate over markets, but the syntax is incorrect in general. Don't use square brackets. Don't walk over all markets if you need just one symbol:

```Python
delay = bitrrex.rateLimit / 1000  # use this for delay
count = 0
while count < 10:
    print(bittrex.fetch_ticker('LTC/BTC'))
    time.sleep(delay)
    count += 1
```
