### ISSUE TITLE
Bittrex create_limit_buy_order INVALID_PERMISSION

### ISSUE THREAD

**Issue by PhinixPhire** [ccxt-dev/ccxt#294]
I'm having trouble placing orders on Bittrex:
The verbose output is monstrously long. Let me know if you need it... 

`    print bittrex.create_limit_buy_order('FUN', 6570, 0.00000519)`

Traceback (most recent call last):
  File "C:\Users\Kenneth\eclipse-workspace\Chank\CCXTtests.py", line 91, in <module>
    print bittrex.create_limit_buy_order('FUN', 6570, 0.00000519)
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 918, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 5037, in create_order
    'market': market['id'],
TypeError: string indices must be integers, not str

**Comment by kroitor** [comment]
@PhinixPhire hi! There's no such pair as `'FUN'` on Bittrex:

```
mbp:ccxt igorkroitor$ python examples/py/symbols.py bittrex | grep FUN

id              symbol          base            quote   

BTC-FUN         FUN/BTC         FUN             BTC            
ETH-FUN         FUN/ETH         FUN             ETH
```

Looks like there are only two pairs, invoving the FUN currency on Bittrex, namely:
1. `'FUN/BTC'`
2. `'FUN/ETH'`

Does this answer your question?

**Comment by PhinixPhire** [comment]
Oops. Unfortunately, I gave you output from a misrepresentative test (should have been FUN/BTC). Here's the trouble I'm having, despite API permissions set appropriately: 

Traceback (most recent call last):
  File "C:\Users\Kenneth\eclipse-workspace\Chank\CCXTtests.py", line 91, in <module>
    print bittrex.create_limit_buy_order('FUN/BTC', 6570, 0.00000519)
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 918, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 5042, in create_order
    response = getattr(self, method)(self.extend(order, params))
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 5166, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.errors.ExchangeError: bittrex {"message":"INVALID_PERMISSION","result":null,"success":false}

**Comment by kroitor** [comment]
@PhinixPhire well, if Bittrex says INVALID_PERMISSION, then you probably confused it and didn't set appropriate permissions on an appropriate keypair. Could you misplace the keys somewhere? If you're using multiple keypairs, check that they are not getting redefined or overrided implicitly by a mistake. Are you sure your keys are set up correctly?

**Comment by PhinixPhire** [comment]
I am sure. I just created a fresh pair with appropriate permissions and have the same error. fetch_balance, on the other hand, works fine.

**Comment by kroitor** [comment]
@PhinixPhire can you post verbose output?

**Comment by PhinixPhire** [comment]
Sure thing!

```
('https://bittrex.com/api/v1.1/market/buylimit?nonce=1507568144243&rate=0.00000519&apikey=[REMOVED]&market=BTC-FUN&quantity=500.00000000', 'GET', 'https://bittrex.com/api/v1.1/market/buylimit?nonce=1507568144243&rate=0.00000519&apikey=[REMOVED]&market=BTC-FUN&quantity=500.00000000', '\nRequest:', {'apisign': '[REMOVED]', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'ccxt/1.9.65 (+https://github.com/kroitor/ccxt) Python/2.7.14'}, None)
('GET', 'https://bittrex.com/api/v1.1/market/buylimit?nonce=1507568144243&rate=0.00000519&apikey=[REMOVED]&market=BTC-FUN&quantity=500.00000000', '\nResponse:', 'Date: Mon, 09 Oct 2017 16:55:45 GMT\r\nContent-Type: application/json; charset=utf-8\r\nContent-Length: 80\r\nConnection: close\r\nSet-Cookie: __cfduid=d47f9b519cb7bb05d99a1de5a72376e0c1507568145; expires=Tue, 09-Oct-18 16:55:45 GMT; path=/; domain=.bittrex.com; HttpOnly\r\nCache-Control: private\r\nContent-Encoding: gzip\r\nStrict-Transport-Security: max-age=15768000\r\nX-XSS-Protection: 1; mode=block\r\nX-Content-Type-Options: nosniff\r\nX-Download-Options: noopen\r\nServer: cloudflare-nginx\r\nCF-RAY: [REMOVED]-LAX\r\n', u'{"success":false,"message":"INVALID_PERMISSION","result":null}')

```

**Comment by kroitor** [comment]
@PhinixPhire , so, if you return to the API keys setup page on their webiste, your trade limit permission for the key looks like the one shown below (the second key on that image), does it?

![bittrex-keys](https://user-images.githubusercontent.com/1294454/31349710-fe2ad1e2-ad2c-11e7-9d60-3184a2bca047.jpg)

**Comment by kroitor** [comment]
I am asking, because I'm able to place orders on Bittrex with ccxt in all three languages (JS, Python and PHP) with an appropriately set up keypair (just checked that). So it must be an issue with:
1. improperly set up permissions
2. misplaced keys somewhere

Can you try a minimal setup with your key:

```Python
import ccxt
bittrex = ccxt.bittrex({
    "apiKey": "YOUR_KEY",
    "secret": "YOUR_SECRET",
    "verbose": True,
})
print(bittrex.create_limit_buy_order('FUN/BTC', 500, 0.00000519))
```

?

**Comment by PhinixPhire** [comment]
I'm terribly sorry. I was under the impression that setting restricted the API trades to a maximum. Changing it did indeed fix the issue. 

Apologies. And Thanks!

**Comment by kroitor** [comment]
@PhinixPhire no problem! Thanks for reporting back. Let us know if you have any other difficulties or questions with it. Cheers!
