### ISSUE TITLE
fetchOrders() for GDAX

### ISSUE THREAD

**Issue by dservais** [ccxt-dev/ccxt#296]
Good evening, did you implement fetchorders fonctions for GDAX?
Best regards

**Comment by kroitor** [comment]
@dservais hi! Not yet, but we will soon. That part of exchange API is currently under active development. We also welcome your pull requests ;)

**Comment by kroitor** [comment]
@dservais if you don't mind, I'd close this issue as being somewhat duplicate to #71 . I suggest discussing everything on this subject in one place ;) Thx!
