### ISSUE TITLE
Binance place order error

### ISSUE THREAD

**Issue by Fcl69** [ccxt-dev/ccxt#298]
Hi,
my code executes fine for several exchanges, but it errors for binance. Here are details:
Exchange: binance, side: sell, symbol: BTC/USD, trade amount: 0.00711675

Traceback (most recent call last):
  File "ccwd.py", line 85, in PlaceOrder
    order = exch.create_market_sell_order(symbol, round(trade_amount, 3))
  File "/lib/python3.5/site-packages/ccxt/exchange.py", line 833, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)
  File "/lib/python3.5/site-packages/ccxt/exchanges.py", line 1401, in create_order
    price = float(price)
TypeError: float() argument must be a string or a number, not 'NoneType'

How can I help it?

**Comment by Fcl69** [comment]
I think I know what the problem is... will update in 5 mins

**Comment by kroitor** [comment]
Hi, @Fcl69 ! 

Can you post verbose output for it?

Try a minimal example:

```Python
import ccxt
binance = ccxt.binance({
    "apiKey": "YOUR_KEY",
    "secret": "YOUR_SECRET",
    "verbose": True,
})
print(bittrex.create_market_sell_order('BTC/USD', 0.00711675))
```

What do you see?

**Comment by kroitor** [comment]
Oh, actually, there's no BTC/USD pair on Binance. They have BTC/USDT (Tether USD), like Poloniex and Bittrex do. Try BTC/USDT.

**Comment by Fcl69** [comment]
yeah, that's what I'm trying right now... stay tuned

**Comment by Fcl69** [comment]
Yes, apparently that was a problem.

There is inconsistency in naming fiat currencies on exchanges (as you've stated in a manual). I have to verify it for every call. For example, bitfinex and hitbtc trade USDT, but refer to it as USD. Poloniex and binance trade USDT and refere to it as USDT.
Looks like I missed this check for binance. My bad, sorry for bothering.

As a suggestion, maybe it could be verified at unified API stage? IF fiat currency is USD and exchange is poloniex|binance|whatever_are_the_rest, fiat=USDT?

**Comment by Fcl69** [comment]
I'm sorry for rushing with my latest comment. The problem remains.
I've done the short version:

```
import ccxt
binance = ccxt.binance({
    'apiKey': 'key',
    'secret': 'secret',
    'verbose': True,
})
print(binance.create_market_sell_order('BTC/USD', 0.00111675))
```
Result:

Vitalys-Laptop:test vitaly.golban$ python3 tt_binance.py
Traceback (most recent call last):
  File "tt_binance.py", line 9, in <module>
    print(binance.create_market_sell_order('BTC/USD', 0.00111675))
  File "/usr/local/lib/python3.6/site-packages/ccxt/exchange.py", line 780, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)
  File "/usr/local/lib/python3.6/site-packages/ccxt/exchanges.py", line 1384, in create_order
    price = float(price)
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by kroitor** [comment]
@Fcl69 Yeah, but you copied an older version of the short example, I've corrected it there for BTC/USDT at the same time ) The reappearing error is again due to BTC/USD instead of BTC/USDT.
So, I guess, this solves your problem?

As for your question:

> As a suggestion, maybe it could be verified at unified API stage? IF fiat currency is USD and exchange is poloniex|binance|whatever_are_the_rest, fiat=USDT?

Are you sure that those three actually trade USD, not USDT ? Because they say it's USDT, and that gets me confused a little. Afaik, USDT are guaranteed to be liquid for the same nominal amount of USD, are they?

**Comment by Fcl69** [comment]
I actually did change it. lol Just to avoid confusions:
`import ccxt
binance = ccxt.binance({

    #('binance', '', '', 'foo', 0.001), #VG Binance
    'apiKey': '213',
    'secret': '1234',
    'verbose': True,
})
print(binance.create_market_sell_order('BTC/USDT', 0.00111675))`

Result:
`test$ python3 tt_binance.py
Traceback (most recent call last):
  File "tt_binance.py", line 9, in <module>
    print(binance.create_market_sell_order('BTC/USDT', 0.00111675))
  File "/usr/local/lib/python3.6/site-packages/ccxt/exchange.py", line 780, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)
  File "/usr/local/lib/python3.6/site-packages/ccxt/exchanges.py", line 1384, in create_order
    price = float(price)
TypeError: float() argument must be a string or a number, not 'NoneType'`


> Are you sure that those three actually trade USD, not USDT ? Because they say it's USDT, and that gets me confused a little. Afaik, USDT are guaranteed to be liquid for the same nominal amount of USD, are they?

Positive. Hitbtc: "Please note that USD stands for USDT cryptocurrency tether.to." https://hitbtc.com/api

Bitfinex: Can't find actual disclosure on a site, but based on my experience of transferring fiats to them, it's USDT. Also word-from-internet-proof:
https://www.reddit.com/r/bitfinex/comments/6yg402/bitfinex_usd_and_usdt_trading_pairs/?st=j8kwwel9&sh=b43af1c1

**Comment by kroitor** [comment]
@Fcl69 but... your result doesn't look like a verbose output to me. Can you try a separate minified sample?

**Comment by kroitor** [comment]
No, never mind, I think I found the problem. I'll fix it asap.

**Comment by Fcl69** [comment]
https://cl.ly/04152g1A1x3y

**Comment by Fcl69** [comment]
ok, cool. Need to get offline, will report back in ~2-3 hours.

**Comment by kroitor** [comment]
The fix is there and it should work in new version 1.9.80+, in 5 minutes. We will be thankful if you report back whether it worked for you or not.

**Comment by Fcl69** [comment]
will do

**Comment by kroitor** [comment]
To check versions for all packages:
```
sudo pip3 list
```

To check the version of ccxt:
```
sudo pip3 list | grep ccxt
```

To update to latest version of ccxt, exactly how you put it:

```
sudo pip3 install -U ccxt
```

**Comment by Fcl69** [comment]
Seems like fix worked. Thank you for resolving it promptly!

To continue on my previous suggestion. I have some time now, so I'd like to clear it up.

So... There are a bunch of exchanges that work with USDT only: bitfinex, binance, hitbtc, poloniex, etc. The problem is they treat symbols differently: BTC/USD (bitfinex, hitbtc) vs BTC/USDT (poloniex, binance) despite the fact it's the same symbol. It's a bit annoying when you have to call ccxt with different symbols based on which exchange you're referring too. It'd be great if ccxt checks and adopt USD vs USDT symbol based to which exchange the call was made. I believe it's already happening in some cases, for example, for Kraken (XBT-> BTC). So I'm suggesting adding USD->USDT where it's applicable.

PS Thanks again for your prompt reply and great support.

**Comment by kroitor** [comment]
@Fcl69 , ok thx for reporting back!

> So... There are a bunch of exchanges that work with USDT only: bitfinex, binance, hitbtc, poloniex, etc. The problem is they treat symbols differently: BTC/USD (bitfinex, hitbtc) vs BTC/USDT (poloniex, binance)

That's for sure...

> despite the fact it's the same symbol

That is something we're not 100% firm with.

> I believe it's already happening in some cases, for example, for Kraken (XBT-> BTC). 

Yep, ccxt already does some corrections, namely these: https://github.com/ccxt-dev/ccxt/wiki/Manual#naming-consistency

> So I'm suggesting adding USD->USDT where it's applicable.

We're not sure that we should force that conversion for all exchanges, but for the ones that clearly claim that (HitBTC) – we think that is appropriate. If we can somehow ensure that USDT is indeed liquid for the same nominal amounts of USD, then there would be no problem to add that correction as well. 

So, I guess, now we need to make sure, that:
1. USD indeed equals USDT
2. USDT is dominating the majority of exchanges, even those that name is USD

This will require some work to find out, because the exchanges themselves are not very supportive... Your help and findings will also be really appreciated!

**Comment by kroitor** [comment]
@Fcl69, but, hey, you can use a shortcut in the meantime, something like:

```Python
def usd_or_usdt(exchange, base):
    symbol = base + '/USD'
    if symbol not in exchange.symbols:
        symbol += 'T'
        if symbol not in exchange.symbols:
            raise Exception('Symbol ' + base + '/USD(T) not found')
    return symbol

symbol = usd_or_usdt(exchange, 'BTC')
print(symbol)
```

;)

**Comment by Fcl69** [comment]
Thank you for providing an update and the workaround solution, currently, I'm using somewhat similar. I will surely let you know about other exchanges I'm facing that hide USDT under USD symbol. Problem is that for most of them I found it hard way ;)

Btw, side topic, is it possible somehow to count calls made to a certain API exchange? I'm getting DDOS protection from bitfinex, for example, from time to time. I assume it's because I'm over the limit requests per minute, but I wonder how to calculate the calls ccxt made on my behalf, so I could somehow manage it.

**Comment by kroitor** [comment]
> Btw, side topic, is it possible somehow to count calls made to a certain API exchange? I'm getting DDOS protection from bitfinex, for example, from time to time. I assume it's because I'm over the limit requests per minute, but I wonder how to calculate the calls ccxt made on my behalf, so I could somehow manage it.

Well, I guess, the best way for you would be to read these two examples, which I just uploaded for you, and compare them to each other:

https://github.com/ccxt-dev/ccxt/blob/master/examples/py/builtin-rate-limiting-long-poller.py
https://github.com/ccxt-dev/ccxt/blob/master/examples/py/manual-rate-limiting-long-poller.py

**Comment by Fcl69** [comment]
Thank you, it helps.

is it safe to assume that any call to exchange.<foo>() is one and only call to API?

**Comment by kroitor** [comment]
@Fcl69 not always, but if it is related to basic market data - there's just one call for 99% of cases. 

For GDAX tickers we have to do two calls to obtain 24h traded volumes. Coinsecure serves the orderbook with two separate endpoints (for bids and asks). Apart from that I don't remember anything else, so, yes, it's mostly 1 request per call. 

More to it:
- The majority of exchanges can tolerate one or two excessive requests above rate limit. What you really need to worry about is keeping private requests below the rate limit, like balance, private order history, placing orders, canceling orders, etc...
- Nobody will penalize you for accidentally hitting the rate limit once or twice a day/hour. But if your software fails to manage that and starts bombing the exchange with requests or hits the limit too often, then you risk being banned.

**Comment by Fcl69** [comment]
Thank you!

**Comment by kroitor** [comment]
@Fcl69 you're welcome! Btw, i'd recommend browsing through other [examples/py](https://github.com/ccxt-dev/ccxt/tree/master/examples/py) as well, you may find something interesting for yourself there. Cheers!

**Comment by miharbines** [comment]
Hi everyone 

i want USDT order this code send btc amount how solve this problem. ? 

thanks for helping
