### ISSUE TITLE
Binance: Timestamp for this request is not valid

### ISSUE THREAD

**Issue by 86chenjie** [ccxt-dev/ccxt#300]
{"code":-1021,"msg":"Timestamp for this request is not valid."}
"ccxt": "^1.9.85",

**Comment by kroitor** [comment]
@86chenjie hi, do you do that sequentially? Can you post a snippet of code to reproduce it?

**Comment by 86chenjie** [comment]
info.ex0 = new ccxt[exchange0](ccxtOptions[exchange0]);
info.balance0 = await info.ex0.fetchBalance();

**Comment by kroitor** [comment]
@86chenjie I just tried it on my side and it works normally for me. Can you try a proxy?

```
info.ex0 = new ccxt[exchange0] ( ccxt.extend (ccxtOptions[exchange0], {
    'proxy': 'https://cors-anywhere.herokuapp.com/',
    'verbose': true,
});
info.balance0 = await info.ex0.fetchBalance();
```

?

**Comment by kroitor** [comment]
https://github.com/sammchardy/python-binance/issues/2

**Comment by kroitor** [comment]
That error on Binance means your system time is out of sync with their clock by >5 seconds... Check your time UTC-alignment. 

Binance doc: 

> An additional parameter, recvWindow, may be sent to specific the number of milliseconds after timestamp the request is valid for. If recvWindow is not sent, it defaults to 5000 millisecond. 

I added support for params in fetchBalance. Try updating to new version (should be available in 5 minutes) and passing a larger recvWindow if your connection to Binance is slow: 

```JavaScript
binance.fetchBalance ({'recvWindow':10000}) // (or 20000)
```

**Comment by kroitor** [comment]
Ok, the new build 1.9.87 has arrived, please update and try the above example to raise your recvWindow if your connection to Binance is slow. Let us know if it helps you or not. Thx!

**Comment by 86chenjie** [comment]
yes. that works. this happen on win 10. my pc failed to sync time with internet. thanks.

**Comment by kroitor** [comment]
@86chenjie ok, thanks for letting us know! Cheers!
