### ISSUE TITLE
Kraken error

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#301]
orderbook2 = exchange2.fetch_order_book (exchange2.market(pair))
  File "C:\Python\lib\site-packages\ccxt\exchanges.py", line 13305, in fetch_order_book
    darkpool = symbol.find('.d') >= 0
AttributeError: 'dict' object has no attribute 'find'

**Comment by kroitor** [comment]
Hi! 

You are getting an error, because you are passing the result of `exchange2.market(pair)` to the `fetch_order_book()`, whereas you should actually pass just the pair (don't wrap the `pair` into `exchange2.market()` call).

Try this:

```
orderbook2 = exchange2.fetch_order_book (pair)
```

Does it work for you?

**Comment by mazertwo** [comment]
Yes, thank you!
