### ISSUE TITLE
Withdrawing funds utilizing memo/destination tag

### ISSUE THREAD

**Issue by PhinixPhire** [ccxt-dev/ccxt#303]
I'm sorry if I'm missing details in the documentation, but I don't see any guidance on how to set params in order to withdraw cryptocurrencies that utilize a mandatory memo/destination tag, such as XRP (Ripple) and DCT (Decent). Has this been unified and what is the syntax in params?

**Comment by kroitor** [comment]
@PhinixPhire hi! 

Most of the calls to the unified API accept an associative dictionary as their last argument, which you can use to override some particular options of your request. 

Just call the unified withdraw (where available) in the following way:

```
exchange.withdraw (currency, amount, address, {
    'your_overrided_param_name': 'your_overrided_param_value',
})
```

All non-unified methods also accept a params dictionary. As you may know, we are still working on unification of that part of their APIs, so we don't have special cases for params of all coins and you need to add those additional params manually, like shown above.

Is it ok, if I close this issue, if the above answers your question?

**Comment by PhinixPhire** [comment]
I have one more question: How do I determine the param name for each currency? I know what they call it on the exchange site, but not how the API references it. Perhaps the API documentation of each exchange? If they don't have clear docs, do I have another means to discover the key?

Thanks, Igor!

**Comment by kroitor** [comment]
@PhinixPhire 

> How do I determine the param name for each currency?

You open their API docs (links are [all here](https://github.com/ccxt-dev/ccxt/wiki/Exchange-Markets)) and find that name from there, by searching *withdraw* or something similar.

> I know what they call it on the exchange site, but not how the API references it.

Not having it unified means that we call the additional *memo/destination* param in the same way, as each particular exchange does call it. So, currently, non-unified = each param name is unique per each exchange.

> Perhaps the API documentation of each exchange?

Yes

> If they don't have clear docs, do I have another means to discover the key?

The docs are mostly clear on that, if that is supported by their API, they usually document the whole set of all possible options.

Let me know if that helps.

Cheers!

**Comment by PhinixPhire** [comment]
Appreciate it very much, @kroitor! Please close the ticket with my sincere Thanks!
