### ISSUE TITLE
fetchOHLCV for Gemini, CEX, Bitstamp...

### ISSUE THREAD

**Issue by s5s** [ccxt-dev/ccxt#306]
Hi,

At present, there are a number of large exchanges for whitch fetch_ohlcv() does not seem to be supported in python (see below). As far as I can see (I've looked at Gemini), this is not an exchange limitation but a ccxt limitation? Assuming I haven't made a mistake so far with my assumptions above, is adding this functionality in the near-term horizon? Is there a development guide on adding a new exchange that I can use to add this functionality?
```
In [18]: import ccxt

In [19]: e = ccxt.bitstamp()

In [20]: e.fetch_ohlcv("BTC/USD")
---------------------------------------------------------------------------
NotSupported                              Traceback (most recent call last)
<ipython-input-20-ba0f4df889f4> in <module>()
----> 1 e.fetch_ohlcv("BTC/USD")

~/code/bitcoin/exchange_api/ccxt/ccxt/exchange.py in fetch_ohlcv(self, symbol, timeframe, since, limit, params)
    829 
    830     def fetch_ohlcv(self, symbol, timeframe='1m', since=None, limit=None, params={}):
--> 831         raise NotSupported(self.id + ' API does not allow to fetch OHLCV series for now')
    832 
    833     def fetchOHLCV(self, symbol, timeframe='1m', since=None, limit=None, params={}):

NotSupported: bitstamp API does not allow to fetch OHLCV series for now```

**Comment by kroitor** [comment]
Hi, @s5s! 

Thanks for opening this issue! 

> At present, there are a number of large exchanges for whitch fetch_ohlcv() does not seem to be supported in python (see below). As far as I can see (I've looked at Gemini), this is not an exchange limitation but a ccxt limitation?

You are absolutely correct, we don't have all methods unified. The library consists of two distinct parts:
- custom API (public and private) - all methods are already implemented and working.
- unified API (public and private) - most, but not all methods are implemented yet.

The Unified API is in progress, but all underlying endpoint methods are already supported out of the box. The Unified API is a wrapper over exchanges' custom public and private endpoint methods. Some of wrapped things may still be missing, because this library is in the stage of active development (being developed right now).

> Assuming I haven't made a mistake so far, is adding this functionality in the near-term horizon?

Yes, we hope to make unify it completely asap (with your help).

> Is there a development guide on adding a new exchange that I can use to add this functionality?

Sure!

Two guides:
- https://github.com/ccxt-dev/ccxt/wiki/Manual
- https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md

Also, check through [issues](https://github.com/ccxt-dev/ccxt/issues?q=is%3Aissue+is%3Aclosed), previously [merged pull requests](https://github.com/ccxt-dev/ccxt/pulls?q=is%3Apr+is%3Aclosed), [examples](https://github.com/ccxt-dev/ccxt/tree/master/examples) and [tests](https://github.com/ccxt-dev/ccxt/tree/master/test) or let us know if you have any difficulty with it.

We really appreciate all help ;)

**Comment by s5s** [comment]
Thanks, let me have a read through this. My immediate question is: in the frontpage, it is mentioned that the python code is generated from JS implementation. Does that mean I need to write JS and then machine-generate the python code?

I feel there is an answer to this question somewhere in the documentation so I feel guilty asking it. Thanks for the amazingly prompt response.

**Comment by kroitor** [comment]
>Thanks, let me have a read through this. My immediate question is: in the frontpage, it is mentioned that the python code is generated from JS implementation. Does that mean I need to write JS and then machine-generate the python code?

Well, no, it doesn't ) First, it is generated automatically upon each build. So it's usually enough to edit the JS only. But don't panic just yet, you don't need to know JS to be able to contribute ))

If you take a closer look at how the code for the exchanges is styled and structured, you will immediately notice, that it's mostly the same style and structure in all three languages (actually it practically the same). So, if you know how to read Python, then you can contribute to ccxt in JS as well ) Just take a look at how same things are done in existing implementations.

But, again, if you don't want to even touch JS, you can still submit edits to the Python version, which can be merged into JS and built from there as easy as doing a direct copy-paste, really. So, you are free to contribute in Python, we'll help merge it anyways. 

But, hey, if you could follow the CONTRIBUTING doc precisely, that'd be awesome! ) Just read the entire guide and you'll understand the code easily in any language. Did you know that you can code in JS and PHP, btw? Well, now you do )

**Comment by kroitor** [comment]
Hi again, @s5s!

----------------------------

#### Bitstamp

Unfortunately, they don't offer an OHLCV endpoint ( So, it's not a ccxt problem , but it's a problem with the exchange. On their webpage they draw candlesticks with their custom Tradeview web interface which is:
- not documented anywhere
- not guaranteed to be consistent or up to date anywhere
- only accessible with their internal authentication + Incapsula CDN tokens and having a lack of information that will require some massive reverse engineering of their website which is an overkill and is beyond the scope of this library for now.

----------------------------

#### Gemini

Same as Bitstamp – no public OHLCV data from their API on their side. It's again not a problem of an exchange, but a problem of the exchange.

Our opinion on this: it's much easier to actually force them to implement and provide proper APIs, having huge profits on fees and not having an adequate support service or an adequate API is a nonsense.

So, for Bitstamp and Gemini there will be no OHLCV until they do something about it.

----------------------------

#### CEX.io

We implemented and unified their OHLCV.

Usage examples:
- [examples/js/fetch-ohlcv-cex.js](https://github.com/ccxt-dev/ccxt/blob/master/examples/js/fetch-ohlcv-cex.js)
- [examples/py/fetch-ohlcv-cex.py](https://github.com/ccxt-dev/ccxt/blob/master/examples/py/fetch-ohlcv-cex.py)

Don't forget to update to v1.9.130 before you use it.

----------------------------

To stress again: two of those three exchanges don't offer any adequate OHLCV access. 

Now that the third has been implemented, I guess, I can close this issue, if you don't mind. Feel free to reopen it or just ask your questions if any. 

Thx for your feedback! Cheers!
