### ISSUE TITLE
okex createMarketBuyOrder error_code 10000

### ISSUE THREAD

**Issue by 86chenjie** [ccxt-dev/ccxt#307]
Request:

```
 { 'User-Agent': 'ccxt/1.9.103 (+https://github.com/kroitor/ccxt) Node.js/8.5.0 (JavaScript)',
  'Content-Type': 'application/x-www-form-urlencoded' } 
api_key=aa8740d4-fb38-4ca3-a1fc-2c7a3daca79c&symbol=ltc_btc&type=buy_market&sign=6B84608FAA5779861D437E200697B560
okex POST https://www.okex.com/api/v1/trade.do
Response:
{"error_code":10000,"result":false}
```

code snippet:

```
    const exchange0 = info.exchanges[0];
    const ex0 = new ccxt[exchange0] ( ccxtOptions[exchange0] );
    const b0 = await ex0.fetchBalance ();
    await ex0.createMarketBuyOrder (info.symbol, info.amount)
```

fetchBalance works, createMarketBuyOrder fail.

**Comment by kroitor** [comment]
@86chenjie hi!

See this thread: for https://github.com/ccxt-dev/ccxt/pull/138

There's a special case for market buy on OKCoin/OKEX. They don't accept an amount there...
You should use the total cost, and pass it in the last param like so:

```
await ex0.createMarketBuyOrder (info.symbol, undefined, info.amount * info.price)
```

We thought of passing the cost inside the *amount* param for marketBuyOrder, but that would add confusion, so we decided to pass cost in the last param.

Let me know if that answers your question.

**Comment by kroitor** [comment]
Actually, I think of rewriting this for the following syntax for more compatibility:
```
await ex0.createMarketBuyOrder (info.symbol, undefined, {
    'cost': info.amount * info.price
})
```

**Comment by 86chenjie** [comment]
thanks, but in this way, i can't control the transaction amount, so i 'll just try to use limit order.

**Comment by kroitor** [comment]
Ok, I changed that implementation a little for more convenience, so the proper syntax is shown in the last example of this thread. Please update to v1.9.104+ in approx 5 minutes if you want to use it.
Unfortunately, for OK* market buys we can't control the amount, only the cost (which is equivalent to limit orders indeed), they just don't allow to set the amount for those types of orders. Sorry.

**Comment by 86chenjie** [comment]
👍
