### ISSUE TITLE
okex fetchOrder error_code 10000

### ISSUE THREAD

**Issue by 86chenjie** [ccxt-dev/ccxt#308]
22351619 'LTC/BTC'
okex POST https://www.okex.com/api/v1/order_info.do
Request:
 { 'User-Agent': 'ccxt/1.9.103 (+https://github.com/kroitor/ccxt) Node.js/8.5.0 (JavaScript)',
  'Content-Type': 'application/x-www-form-urlencoded' } api_key=aa8740d4-fb38-4ca3-a1fc-2c7a3daca79c&symbol=ltc_btc&sign=FCAA67DF4F452419FE27D3FE6CA78CAE
okex POST https://www.okex.com/api/v1/order_info.do
Response:
{"error_code":10000,"result":false}

code snippet:
   const orderId = 22351619;
    console.log (orderId, info.symbol);
    const order = await ex0.fetchOrder (orderId, info.symbol);    
    console.log (order);

**Comment by kroitor** [comment]
Hi, @86chenjie ! Thank you again for your helpful feedback! This issue is now fixed in 1.9.109+. Let us know if you experience any difficulty with it, I tested it and it should work normally. Cheers!

**Comment by 86chenjie** [comment]
work now. thanks
