### ISSUE TITLE
is Order Structure's average field always available?

### ISSUE THREAD

**Issue by 86chenjie** [ccxt-dev/ccxt#312]
```
{ info:
   { amount: 0.1,
     avg_price: 0.01047286,
     create_date: 1507721878000,
     deal_amount: 0.1,
     order_id: 22351619,
     orders_id: 22351619,
     price: 0.01068231,
     status: 2,
     symbol: 'ltc_btc',
     type: 'buy' },
  id: 22351619,
  timestamp: 1507721878000,
  datetime: '2017-10-11T11:37:58.000Z',
  symbol: 'LTC/BTC',
  type: 'limit',
  side: 'buy',
  price: 0.01068231,
  average: 0.01047286,
  amount: 0.1,
  filled: 0.1,
  remaining: 0,
  status: 'closed',
  fee: undefined }
```
that's order info from okex.
'average' field not mentioned in doc https://github.com/ccxt-dev/ccxt/wiki/Manual#order-structure
for me, i don't care about the 'price' field, which i guess is the price i create order for.
instead i need to know the average transaction price.

**Comment by kroitor** [comment]
Hey again ) Currently, the average is not guaranteed → therefore it's not documented, but we are going to export it as well (where available). We currently guarantee `cost` which is usually equal to the actual traded price / filled, so if filled is > 0 and you divide the cost by filled, you can get the average price. But that is, again, not always the case, because the exchanges themselves are not clear on that.

The problem with unifying that data is caused by the lack of info and docs from the exchanges, which don't state explicitly, whether their returned fields include fees or not, how the cost is calculated and how the price/amount precision is controlled. We have to reverse-engineer that logic often, for each exchange separately. And for that we need testing funds. But we are making progress on our way to that goal. We think, in the end it will be possible to guarantee 'average'.

Let me know if the above answers your question. Cheers!

**Comment by kroitor** [comment]
I've added the missing cost field to OK*, and I think I'm going to add the average to all other exchanges as well. Thx!

**Comment by 86chenjie** [comment]
thanks 👍

**Comment by 86chenjie** [comment]
@kroitor  btw, do you find a way to get average price for market order in binance?
i checked the fetchOrder api result, price field is zero.

**Comment by kroitor** [comment]
@86chenjie if you fetch orders, they indeed return zeroes for market orders, so this is not something we can fix in the fetchOrder method. Here's the example structure of a market order returned from Binance:

```
{      info: {        symbol: "ETHBTC",
                     orderId:  8782435,
               clientOrderId: "VvpdjBpynXY5kw16fGmmRD",
                       price: "0.00000000",
                     origQty: "0.05100000",
                 executedQty: "0.05100000",
                      status: "FILLED",
                 timeInForce: "GTC",
                        type: "MARKET",
                        side: "SELL",
                   stopPrice: "0.00000000",
                  icebergQty: "0.00000000",
                        time:  1507774371365            },
         id:   "8782435",
  timestamp:    1507774371365,
   datetime:   "2017-10-12T02:12:51.365Z",
     symbol:   "ETH/BTC",
       type:   "market",
       side:   "sell",
      price:    0,
     amount:    0.051,
       cost:    0,
     filled:    0.051,
  remaining:    0,
     status:   "closed",
        fee:    undefined                                  }
```

But you can find out the actual market price that was used to fill the order from your private trades (Binance has a unified `fetchMyTrades()` method for that, like many other exchanges do).

If you take a look at the structure of a trade:
```
{      info: {              id:  1984215,
                       orderId:  8782435,
                         price: "0.06317800",
                           qty: "0.05100000",
                    commission: "0.00000322",
               commissionAsset: "BTC",
                          time:  1507774371365,
                       isBuyer:  false,
                       isMaker:  false,
                   isBestMatch:  true           },
  timestamp:    1507774371365,
   datetime:   "2017-10-12T02:12:51.365Z",
     symbol:   "ETH/BTC",
         id:   "1984215",
      order:   "8782435",
       type:    undefined,
       side:   "sell",
      price:    0.063178,
       cost:    undefined,
     amount:    0.051,
        fee: { cost: 0.00000322, currency: "BTC" } }
```

So, your code should look something like this: 

```
const orders = await binance.fetchMyOrders('ETH/BTC')
const order = orders[0]
if (order['type'] == 'market') {
    const trades = await binance.fetchMyTrades('ETH/BTC')
    const tradesByOrderId = ccxt.groupBy (trades, 'order')
    const orderTrades = tradesByOrderId[order['id']];
    console.log (orderTrades)  // ← will print all trades for that order
    let filled = 0; // amount
    let price = 0; // sum of prices
    orderTrades.foreach (trade => {
        filled += trade['amount'];
        price += trade['price'];
    })
    console.log ('Average cost of order', order['id'], '=', price / filled)
}

```

Let me know if that helps

**Comment by kroitor** [comment]
@86chenjie ↑ this is because an order can be filled in more than one trade (partial fill), but, I guess, you know that.

**Comment by kroitor** [comment]
@86chenjie I also fixed the cost field for it, so you can now do:

```
    // ...
    const totalCost = orderTrades.reduce ((a, b) => a + b['cost'], 0)
    const averageCost = totalCost / orderTrades.length
    // ...
```

**Comment by 86chenjie** [comment]
@kroitor   totalCost / orderTrades.length
orderTrades.length         not make sense to me :)

**Comment by kroitor** [comment]
@86chenjie yep, I edited it a little, so now it should make sense ;) See the updated version above.

**Comment by kroitor** [comment]
Let me know if you have other questions left ) Cheers!

**Comment by 86chenjie** [comment]
@kroitor  okex fetchOrders  api not work, but in okex api doc, there is a api to query orders.
https://www.okex.com/rest_api.html

# Request
POST https://www.okex.com/api/v1/orders_info.do
# Response
{
	"result":true,
	"orders":[
		{
			"order_id":15088,
			"status":0,

**Comment by kroitor** [comment]
@86chenjie is fetchOrders the only method that does not work?

**Comment by kroitor** [comment]
@86chenjie yep, looks like they need multiple order ids for that method... And we should call order_history instead, but it's only available for spot market. What do you think about it?

**Comment by kroitor** [comment]
@86chenjie you can actually use their fetchOrders right away by doing something like this:
```JavaScript
okex.fetchOrders ('LTC/BTC', {
    'order_id': [ 'order123', 'order456', 'order789' ].join (','),
})
```

**Comment by kroitor** [comment]
Let me know what you think we should do:
1. rewrite fetchOrders to use order_history.do
2. leave fetchOrders as is
3. rewrite fetchOrders to use orders_info.do and if order_id is not supplied to fallback to order_history.do
?

**Comment by 86chenjie** [comment]
1 is what i need. thanks

**Comment by kroitor** [comment]
@86chenjie, ok, we'll upload that.

**Comment by 86chenjie** [comment]
@kroitor  how's this change going?

**Comment by kroitor** [comment]
@86chenjie we uploaded that (should be there in 5 mins), but there's more to OKCoin fetchOrders, looks like they require to specify an open or closed status when querying, so there are three unified methods:
1. fetchOpenOrders (...)
2. fetchClosedOrders (...)
3. fetchOrders that requires either an order_id param or a status/type param

**Comment by 86chenjie** [comment]
that's fine. thanks! 👍

**Comment by kroitor** [comment]
@86chenjie ok, we'll be happy if you report back, as always. It worked for me, but there still may be some caveats. If you have an error with it, we'll need to see the verbose output. Thx!

**Comment by kroitor** [comment]
@86chenjie v1.9.128

**Comment by 86chenjie** [comment]
@kroitor   
console.log(await ex0.fetchClosedOrders(info.symbol));
 TypeError: this.fetchOrdersByStatus is not a function

not work

**Comment by kroitor** [comment]
@86chenjie sorry, a left over. Just a sec.

**Comment by kroitor** [comment]
@86chenjie ok, v. 19.129 now %)

![giphy-downsized](https://user-images.githubusercontent.com/1294454/31527393-880b5b0c-afd5-11e7-8a7d-76fc03f53f75.gif)

**Comment by 86chenjie** [comment]
👍  works

**Comment by kroitor** [comment]
Reference: #71
