### ISSUE TITLE
Warning: Declaration of ccxt\{exchangeId}::fetch_tickers() should be compatible with ccxt\Exchange::fetch_tickers($symbols, $params = Array)

### ISSUE THREAD

**Issue by zNoobs** [ccxt-dev/ccxt#313]
Hello,
I got this error for many exchanges when I'm using the ccxt php library (here the errors of the  'include "build/ccxt.php";'):
```
( ! ) Warning: Declaration of ccxt\acx::fetch_tickers() should be compatible with ccxt\Exchange::fetch_tickers($symbols, $params = Array) in C:\wamp64\www\crypto\ccxt-master\build\ccxt.php on line 2111
( ! ) Warning: Declaration of ccxt\bithumb::fetch_tickers($currency = 'BTC') should be compatible with ccxt\Exchange::fetch_tickers($symbols, $params = Array) in C:\wamp64\www\crypto\ccxt-master\build\ccxt.php on line 4550
...
```

Do I have to change all declarations?

Best regards.

**Comment by zNoobs** [comment]
Thanks, fast!
Another declaration problem, should change the line 14195 to:
    public function parse_ticker ($ticker, $market = null) {

And it works!

Best regards.

**Comment by zNoobs** [comment]
Should I commit this change?

**Comment by kroitor** [comment]
Hi, @zNoobs! )

This issue should be fixed now, thx for your help and your feedback! Let us know if you experience any other difficulties with it. Cheers!

**Comment by kroitor** [comment]
Oh, forgot to say: your contributions are welcome! We will be happy if you submit a PR ) Just make sure to first read these two very carefully:  

- https://github.com/ccxt-dev/ccxt/wiki
- https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md

Thx again!
