### ISSUE TITLE
HitBTC buy/sell order fails

### ISSUE THREAD

**Issue by Fcl69** [ccxt-dev/ccxt#314]
Hi,

here is my code:

```
import ccxt
hitbtc = ccxt.hitbtc({
    "apiKey": "key",
    "secret": "secret",
    "verbose": True,
})
print(hitbtc.create_market_sell_order('BTC/USD', 0.01))
```
ccxt fails...

PS Key & nonce is fine, I can pull balance data, for example.

**Comment by kroitor** [comment]
Hi, @Fcl69!
I've uploaded a slightly edited version of it... can you please try it again and report? It should work now.
Cheers!

**Comment by Fcl69** [comment]
It did work! Thank you!

**Comment by kroitor** [comment]
@Fcl69 ok, but, please, be aware, that there's a little more to it:

1. HitBTC has a `timeInForce` order parameter, that is a setting that controls the execution of the order (how HitBTC should treat and fill the order):

```
GTC (Good-Til-Canceled): the order will stay open or partially closed until filled or canceled by user
IOC (Immediate-Or-Cancel): the order will either fill immediately or will be canceled automatically
FOK (Fill-Or-Kill): the order will either be filled entirely or will expire
DAY (Day): the order will either be filled in 24 hours or will expire
GTD (Good Till Date): the order will expire on specific date
```

2. The default execution type for limit orders the default in HitBTC and ccxt is GTC.

3. For market orders HitBTC allows IOC or FOK only. The default in HitBTC and ccxt is FOK.
If you need IOC execution, then you should pass that as an extra param with your market order, like so:

```
hitbtc.create_market_sell_order('BTC/USD', 0.01, { 'timeInForce': 'FOK' }) # default
hitbtc.create_market_buy_order('BTC/USD', 0.01, { 'timeInForce': 'IOK' })


hitbtc.create_limit_sell_order('BTC/USD', 0.01, { 'timeInForce': 'GTC' }) # default
hitbtc.create_limit_buy_order('BTC/USD', 0.01, { 'timeInForce': 'IOC' })
```

Let us know if you have any questions or difficulties left. Thx!
