### ISSUE TITLE
(hitbtc) order amount should be evenly divisible

### ISSUE THREAD

**Issue by PhinixPhire** [ccxt-dev/ccxt#316]
```
Selling 59.3 SWT to hitbtc for 0.00029004 BTC
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Kenneth\eclipse-workspace\Chank\trade-daemon.py", line 105, in sell_xfer
    print destexch.create_limit_sell_order(market, xfer_target_balance, maxprice)
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 945, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 11788, in create_order
    raise ExchangeError(self.id + ' order amount should be evenly divisible by lot unit size of ' + str(market['lot']))
ExchangeError: hitbtc order amount should be evenly divisible by lot unit size of 1.0
```

I know what this error means, and I know how it fix it, but my question is... how can I tell which precision level HitBTC prefers for each coin? Is that information available anywhere in ccxt, or will I need to construct a database table for tracking these requirements of each exchange? 

Thanks so much!

**Comment by kroitor** [comment]
Hi!

> Is that information available anywhere in ccxt,

Yep ;)

> how can I tell which precision level HitBTC prefers for each coin?

You can tell that from the `lot` property of each particular market:

```Python
print(hitbtc.markets['BTC/USD']['lot'])  # ?
```

![hitbtc-lot](https://user-images.githubusercontent.com/1294454/31545176-fe2c676c-b026-11e7-86cb-2aff6579e572.jpg)

**Comment by PhinixPhire** [comment]
You're my hero, @kroitor 
Thanks so much! That's absolutely perfect for my needs.

**Comment by kroitor** [comment]
@PhinixPhire you're welcome! )
