### ISSUE TITLE
Add some interesting exchanges

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#317]
Bit-Z  $11,008,293 (24h turnover) https://coinmarketcap.com/exchanges/bit-z/
Allcoin $5,414,265 https://coinmarketcap.com/exchanges/allcoin/
LocalTrade $1,574,955 https://coinmarketcap.com/exchanges/localtrade/

**Comment by kroitor** [comment]
Hi, @mazertwo !

Thanks for your suggestion!

After a brief review:

1. Bit-Z – I can't find any private (trading) API on their website, can you?
2. Allcoin – will integrate
3. LocalTrade – can't find any API docs at all, can you?

**Comment by mazertwo** [comment]
Ahahah, exchanges without API. Bit-Z doesnt have trading part API. Wow, it is not "wild west", it's more interesting phenomenon :) Thank you for fast answer, as usual!

**Comment by kroitor** [comment]
Ok, so, of three exchanges suggested, two have no adequate API, and the third one has been integrated. So, I guess, I can close this issue now. Let us know if you have any questions with it. Cheers!

**Comment by mkutny** [comment]
@mazertwo , do you have an experience with allcoin?

If you do, could you tell their fee schedule? I would integrate it into `ccxt`.

From their website I read:
> Transaction Fee - Buy: 0% Sell: 0.2%

All other exchanges stick to maker/taker model, I've never seen buy/sell approach before and it seems quite strange. Do you know if it's true or it's a translation issue?

Thanks!

**Comment by jjhesk** [comment]
backing up some allcoin info:
Di Deng, Chief Executive Officer | Telephone No.: 604‐639‐1285 | Cascadia Consumer Electronics Corp. (the “Company”) | Suite 1552, 701 West Georgia Street Vancouver, British Columbia V7Y 1C6
