### ISSUE TITLE
How i can fetch Poloniex margin balance and made margin order?

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#318]
Hello, great ccxt team!

How can i fetch Poloniex margin balance and made margin order?

In Bitfinex margin a add {'type': 'limit'}

Thank you!

**Comment by mazertwo** [comment]
{'type': 'margin'} :)

**Comment by kroitor** [comment]
Hi!

> How can i fetch Poloniex margin balance and made margin order?

Have you tried doing what's written in the Manual? Do you see margin trading methods are there?

```Python
import ccxt
print(dir(ccxt.poloniex()))
```

> Seem's margin trading on the Poloniex is not implemented in ccxt now.

CCXT implements all of their endpoint methods out of the box, including those for margin trading. You just need to read the Manual once and for all. If you follow it carefully, you will be able to find all answers to your questions pretty quickly. This is what learning is about: read, try, think, reread, retry, rethink, etc...

**Comment by mazertwo** [comment]
Bitfinex margin trading works with just adding one parameter {'type': 'limit'}.
I tihnk, its wery usefull.

Can you write example, how can i get margin position? poloniex.__getattribute__('private_post_getmarginposition')?
how can i put margin order to Poloniex?  'privatePostMarginBuy'?

**Comment by kroitor** [comment]
From Poloniex:

> **getMarginPosition**
> Returns information about your margin position in a given market, specified by the "currencyPair" POST parameter. You may set "currencyPair" to "all" if you wish to fetch all of your margin positions at once. If you have no margin position in the specified market, "type" will be set to "none". "liquidationPrice" is an estimate, and does not necessarily represent the price at which an actual forced liquidation will occur. If you have no liquidation price, the value will be -1.

So, to fetch all your margin position, you need to do the following:

```Python
import ccxt
poloniex = ccxt.poloniex ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})


# the line below is in underscore notation
print(poloniex.private_post_getmarginposition ({ 'currencyPair': 'all' }))

# the line below is the same as above, but in camelcase notation
print(poloniex.privatePostGetMarginPosition ({ 'currencyPair': 'all' }))

# if you want a specific currency instead of all currencies
# you will have to either put a poloniex pair inside
# or convert a unified symbol name to poloniex pair id, by preloading markets first
poloniex.load_markets()
print(poloniex.privatePostGetMarginPosition ({
    'currencyPair': poloniex.marketId('BTC/USDT')
}))
```

Does the above answer your question?

**Comment by mazertwo** [comment]
Yes, thank you for all what you do!

**Comment by kroitor** [comment]
Ok, let us know if you have any other difficulties with it, i'm closing this for now if you don't mind. Cheers!

**Comment by ChacoLv** [comment]
@kroitor how can I get my bitfinex margin position information?
I try to do it by exch.fetch_my_trades(symbol=symbol,params=params)
params = {'type': 'trading'}
but it result is all my history order information ,is not my real margin position information.

**Comment by kroitor** [comment]
@ChacoLv answered here: https://github.com/ccxt/ccxt/issues/255#issuecomment-418307476

**Comment by gelinger777** [comment]
what about getting krakens PrivatePostGetPositions?

**Comment by kroitor** [comment]
@gelinger777 you can call it with CCXT using the implicit API methods: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods, just like any other endpoint.
