### ISSUE TITLE
buy/sell operation, Error: Place order error: Insufficient funds.

### ISSUE THREAD

**Issue by evgen-y2k** [ccxt-dev/ccxt#321]
Hi. 
Periodically for SELL/BUY operations I see this error: 
`
ExchangeError ('cex {"error":"Error: Place order error: Insufficient funds."}',)
`

Very strange because balanse is enough for operation.
If I restart script, error not repeat.
P.S. CEX.IO market

**Comment by kroitor** [comment]
Hi, @evgen-y2k ! Can you paste a minimal code snippet to reproduce the problem?

**Comment by evgen-y2k** [comment]
I can not reproduce this yet. I'm trying to determine the cause of the error. Today 9 hours the script worked without errors. During the last hour the error appeared 3 times.

**Comment by kroitor** [comment]
@evgen-y2k do you have funds on open orders? And how do you check the balance? In order to determine the free amounts, you need to look at 'free' balances. Unfortunately, it's impossible to help until we see some code...

**Comment by evgen-y2k** [comment]
Yes, I fully understand how it work! I describe situation:
- My script place 5-7 BUY orders. Work correct
- If price go up, my script make cancellation of all orders and place new 5-7 orders with new price. At this time can be error for BUY operation. For 5-7 orders script use only 20% of my deposit.  There is always a supply of money.

**Comment by evgen-y2k** [comment]
I think that the possible cause of the error is the limitation on the number of CEX.IO requests (600 requests for 10 minutes maximum). Now I inserted more delay between all operations with orders and started script again. I wait errors ...

**Comment by kroitor** [comment]
@evgen-y2k currently, it's impossible to tell from your text description where the error is. Unfortunately, we can't debug your trading logic for you, so you need to make a minimalistic test to reproduce the bug. Most likely, you have an error with evaluating free and used balances at some stage. I am closing this until you're able to reproduce it. Feel free to reopen it or just continue asking your questions. We will be happy to help, where possible.

Also, if you are having a rate limiting issues, please read this:

https://github.com/ccxt-dev/ccxt/wiki/Manual#rate-limit
https://github.com/kroitor/ccxt/wiki/Manual#authentication
https://github.com/kroitor/ccxt/wiki/Manual#overriding-the-nonce
https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

**Comment by kroitor** [comment]
P.S. and this: https://github.com/ccxt-dev/ccxt/issues/319

**Comment by evgen-y2k** [comment]
Ok. When I found cause of this error and will can reproduce, I will open new ticket with full description and code example. About your links abowe: I checked this possible cause before opening ticket and all right. I use override nonce in my script (work fine), rate limit my script take from market and use it for check (`
MIN_LOT_SIZE = float(cex.load_markets()['%s/%s' % (CUR1,CUR2)]['info']['minLotSize'])
.....
if float(long_calc_min_order_volume()) / BID < MIN_LOT_SIZE:
`), 
without correct auth script cen't not work e.t.c....

**Comment by kroitor** [comment]
@evgen-y2k 

> When I found cause of this error and will can reproduce, I will open new ticket with full description and code example.

You can simply reopen this issue, so to keep it simple. We'll stand by for more info from you to reproduce it.

**Comment by evgen-y2k** [comment]
Ok, I found mistake! It is problem with rounding on CEX.IO. In the Rounds Policy described:

> 14.1. For all financial calculations, CEX.IO uses a rounding policy in the favour of the Platform. CEX.IO rounds the fiat currencies to the 2nd digit after the separator. Rounding policy for cryptocurrencies varies depending on cryptocurrency.

> 14.4. Cryptocurrencies with rounding to 8th digit after separator are BTC, LTC, NMC.

Nothing about ETH, but for ETH/USD pair it is not correct. For this pair CEX rounds to 6 digit after separator and to down! Not know why. ETH/EUR pair have normal rounds to 8 digits.

**Comment by kroitor** [comment]
@evgen-y2k ok, so, do we need to change something in ccxt?

**Comment by evgen-y2k** [comment]
I think no. It is problem of CEX.

**Comment by kroitor** [comment]
@evgen-y2k ok, let me know if you have any other difficulties with the library. Thx!
