### ISSUE TITLE
Exchanges with short enabled

### ISSUE THREAD

**Issue by wendelmaques** [ccxt-dev/ccxt#323]
Hello everyone, first off thank's for this library, it has a lot of potential.

I wonder if it's possible to add an extra column in exchange-capabilities.js to indicate whether a exchange allows SHORT orders or not.

I believe that if ccxt can indicate if a exchange allows SHORT orders is big differential in relation to others libraries, because this info does not exist in other libraries and take a lot of research to discover this info.

Today I'm using https://www.cryptocompare.com/ and preparing to switch to ccxt in a near future.

**Comment by kroitor** [comment]
Hi, @wendelmaques ! Thanks for your feedback and for the proposal! I totally agree with you and we will add that indicator shortly. Will let you know as soon as it's available. Hopefully, soon. If that answers your question, I would close this issue for now if you don't mind. Stay tuned for updates )

**Comment by wendelmaques** [comment]
Thank you Igor, you answered my question, very quickly, as usual.
