### ISSUE TITLE
Bittrex fetchOpenOrders is missing the price field

### ISSUE THREAD

**Issue by anandanand84** [ccxt-dev/ccxt#327]
As you can see in the attached image the limit price is available in the info. But not available in the price field.

![image](https://user-images.githubusercontent.com/5538452/31645238-9dcb3c8a-b2c0-11e7-86c3-f429569a1281.png)

**Comment by kroitor** [comment]
Hi, @anandanand84 ! Thx for reporting, we will fix that (soon)!

**Comment by kroitor** [comment]
@anandanand84 actually... which version of ccxt library do you have?

**Comment by anandanand84** [comment]
@kroitor, Doesn't seem to have this issue with the latest version. Thanks!

**Comment by kroitor** [comment]
@anandanand84 Cheers! Thx for reporting back! ;)
