### ISSUE TITLE
Huobi PRO empty fetchBalance return

### ISSUE THREAD

**Issue by gavin369** [ccxt-dev/ccxt#328]
I'm a beginner. I want to be a bot. I want to ask you something! I don't show my account balance with console.log (await huobipro.fetchBalance ()),
![image](https://user-images.githubusercontent.com/26453791/31654646-338c082e-b359-11e7-8d5d-33f743c8c22e.png)

![image](https://user-images.githubusercontent.com/26453791/31654328-5317d156-b358-11e7-8557-6dfa7be0285c.png) 

but actually there is a balance,

![image](https://user-images.githubusercontent.com/26453791/31654373-79a91d66-b358-11e7-971a-9080e065a2a6.png)

excuse me, what did I make wrong? Thank you

**Comment by kroitor** [comment]
Hi, @gavin369 ! Can you add the following line please to see what huobi actually returned to ccxt?

```
let huobipro = new ccxt.huobipro ({
    apiKey: 'YOUR_KEY',
    secret: 'YOUR_SECRET',
    verbose: true, // ←---------------------- this line added to see more verbose info
})

// ... then call the balance like you did in your code and check the onscreen output

```

Paste the output here, please. Use triple backticks for pasting code like for more readability:

&#96&#96&#96
code
&#96&#96&#96

**Comment by gavin369** [comment]
&#96&#96&#96
'use strict';
var ccxt = require ('ccxt');
var async = require('async');
console.log ('添加交易所名称',ccxt.exchanges[56] )
console.log ('添加交易所个数',ccxt.exchanges.length)
var start = async function () {
    // 在这里使用起来就像同步代码那样直观
    let huobipro = new ccxt.huobipro ({
        apiKey: 'key',
        secret: 'secret',
    })
    while (true){
        ticker = (await huobipro.fetchTicker('LTC/BTC')).info;
        Balance = await huobipro.fetchBalance ();
        console.log (Balance)
        //console.log ('买1价',ticker.ask[0],'卖1价',ticker.bid[0],'买1深度',ticker.ask[1],'卖1深度',ticker.bid[1]);
        //console.log (Balance)
        await sleep(3000);
    }
};
start();

&#96&#96&#96

**Comment by kroitor** [comment]
You should not put &#96 there, use the backtick (&#96;) on your keyboard 3 times in the beginning and 3 times in the end ) That's not a problem, just letting you know for future use ;)

The code is ok, but please paste the verbose output as in my previous post. We need you to add that `verbose: true` line and run your code again, then paste the output here.

**Comment by gavin369** [comment]
Okay, I got it. First contact with GitHub. sorry！

**Comment by kroitor** [comment]
@gavin369 no problem at all ) Welcome ) We will stand by to see your verbose output.

**Comment by kroitor** [comment]
@gavin369 did you manage to get verbose output? We will be waiting to see your output in verbose mode, like written above.

**Comment by kroitor** [comment]
@gavin369 alternatively, after you fetch the balance you can simply do:
```
console.log (Balance['info']); 
```
... and paste the output here.

**Comment by gavin369** [comment]
Now I'm not using console.log, but it's also printing information!

```
'use strict';
var ccxt = require ('ccxt');
var async = require('async');
verbose: true
console.log ('添加交易所名称',ccxt.exchanges[56] )
console.log ('添加交易所个数',ccxt.exchanges.length)
var start = async function () {
    // 在这里使用起来就像同步代码那样直观
    let huobipro = new ccxt.huobipro ({
        apiKey: 'apiKey',
        secret: 'secret',
        verbose : true,
    })

    while (true){
        //ticker = (await huobipro.fetchTicker('LTC/BTC')).info;
        Balance = await huobipro.fetchBalance();
        //console.log (Balance);
        //console.log (Balance)
        //console.log ('买1价',ticker.ask[0],'卖1价',ticker.bid[0],'买1深度',ticker.ask[1],'卖1深度',ticker.bid[1]);
        //console.log (Balance)
        await sleep(3000);
    }

};
```
![image](https://user-images.githubusercontent.com/26453791/31659238-05a9068e-b366-11e7-97e9-0f8e7cf5fd2b.png)

**Comment by kroitor** [comment]
@gavin369 ok, thank you for the info! I will now debug it a little and will get back to you shortly.

**Comment by kroitor** [comment]
@gavin369 ok, this was a bug in balance parsing, but now it's fixed and Huobi should be working normally. Please don't forget to update the ccxt library to version 1.9.163+ (`npm update ccxt` in your package folder) and retry again. We will be happy if you report whether it works for you or not. Thx again for your participation!

P.S. Next time don't paste text in images and screenshots, paste code and verbose output in text enclosed with 3 backticks (&#96;) for all text information. When we are programming, it is much better and much easier to read and edit, if both the code and the output are copied and pasted in text, not as an image. Anyway, thanks for your help! ;) Let us know if you have any other questions or difficulties with it. The library is under heavy development and we really appreciate your feedback! )

**Comment by gavin369** [comment]
Okay，i know！ Thank you very much.
