### ISSUE TITLE
southxchange.hasWithdraw False, but API supports withdrawals

### ISSUE THREAD

**Issue by PhinixPhire** [ccxt-dev/ccxt#332]
Sorry to submit multiple issues at once. When I initialize southxchange from an older version of ccxt (since I'm experiencing the issue described in [#331](https://github.com/ccxt-dev/ccxt/issues/331)), I'm seeing that southxchange.hasWithdraw == False

But southxchange API seems to support withdraw:
https://www.southxchange.com/Home/Api#withdraw

Can we get the unified method implemented for southxchange withdrawals?

**Comment by kroitor** [comment]
Sure, will add it shortly. As you may know, we don't have them all unified, so there may be hasWithdraw = false, where it is not implemented yet. But we will implement it quickly.

**Comment by kroitor** [comment]
Here's a quick overview of the current state:

<img width="1478" alt="screen shot 2017-10-17 at 20 01 01" src="https://user-images.githubusercontent.com/1294454/31678162-ed415b7c-b375-11e7-980b-501d4906d2b9.png">

**Comment by PhinixPhire** [comment]
Beautiful! That image is very helpful. 

I'm going to be going through each and every exchange today determining viability for my project. I'll be noting which ones do not have withdrawal set up in ccxt while their withdrawal capability _is_, in fact, available through their API. 

I think I'd like to try and learn how I can contribute Pull requests to implement some of these if I find myself capable... it would be an honor to contribute to ccxt in that manner. I've got to read up on the process first, but hopefully I can get it working. 

Thanks!

**Comment by kroitor** [comment]
> I'll be noting which ones do not have withdrawal set up in ccxt while their withdrawal capability is, in fact, available through their API.

That info itself would be really helpful in our work ;)

> I think I'd like to try and learn how I can contribute Pull requests to implement some of these if I find myself capable... 

And I think it would be awesome to see some PRs from you! )

> I've got to read up on the process first, but hopefully I can get it working.

Sure, no problem, feel free to ask, we actually welcome all pull requests, and any help is appreciated! If you feel like going for it, read previous pull requests and issues by other people, there's a lot of useful info you may find interesting for understanding the inner workings of the library better (to have better control over your finance).

Also, this: https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md 

In the meantime we will try to upload the withdraw() for southxchange... ;)

**Comment by PhinixPhire** [comment]
Thanks, Igor! I'll read up and get back to you. I'd appreciate the addition of southxchange in the meantime, and I'll let you know if I have any difficulties. 

One question before I get started... does it matter that I only know Python 2.7? Can I submit a fix in just the one language and still be helpful?

**Comment by kroitor** [comment]
> One question before I get started... does it matter that I only know Python 2.7? Can I submit a fix in just the one language and still be helpful?

We actually thought on answering that question beforehand, in the CONTRIBUTING doc ;)

https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

> The ccxt library is available in three different languages (more to come). We encourage developers to design portable code, so that a single-language user can read code in other languages and understand it easily. This helps the adoption of the library. The main goal is to provide a generalized, unified, consistent and robust interface to as many existing cryptocurrency exchanges as possible.

> At first, all language-specific versions were developed in parallel, but separately from each other. But when it became too hard to maintain and keep the code consistent among all supported languages we decided to switch to what we call a master/slave process. There is now a single master version in one language, that is JavaScript. Other language-specific versions are syntactically derived (transpiled, generated) from the master version. But it doesn't mean that you have to be a JS coder to contribute. The portability principle allows Python and PHP devs to effectively participate in developing the master version as well.

**Comment by kroitor** [comment]
The support for withdraw has been added to SouthXchange implementation in ccxt as of version 1.9.168+. Please report if you have any difficulties with it, though, it should work normally. Thx again!

**Comment by kroitor** [comment]
I would close this issue for now, if you don't mind. The implemented should work anyway. Let us know, please, whether it does or does not work for you. Thx again! Feel free to reopen this if needed or just ask questions, if any. Cheers!

**Comment by PhinixPhire** [comment]
Yes, it's fine to close. So sorry for the delay... I've been swimming in other tasks trying to get this automation functional. Right now the Ethereum I sent to test southxchange withdraw with is stuck in limbo. It's on the blockchain, but I can't use it yet. Will report back soon.

**Comment by kroitor** [comment]
Thx!
