### ISSUE TITLE
Help implementing bitstamp fetchOrders

### ISSUE THREAD

**Issue by jgordor** [ccxt-dev/ccxt#342]
Hi,

I'm trying to implement fetchOrder/s for bitstamp:

Added:
```js
    'hasFetchOrder': true,
    'hasFetchOrders': true,
...
    'api': {
        'public': {
            'get': [
...
            ],
        },
        'private': {
            'get': [
                'transactions/',
                'transactions/{pair}/',
            ],
...
    async fetchOrders (symbol = undefined, params = {}) {
        await this.loadMarkets ();
        let market = this.market (symbol);
        let pair = market ? market['id'] : '';
        const orders = await this.privateGetTransactionsPair (this.extend ({
            'pair': this.marketId (symbol),
        }, params));
``

But I'm always receiving:
```js
ERROR [Exchange Not Available Error] bitstamp GET https://www.bitstamp.net/api/v2/transactions/btcusd/  Request with GET/HEAD method cannot have body
```

Do you know what could be the problem?

Thanks!

**Comment by kroitor** [comment]
Hi, @jgordor !

There's no such endpoint for private orders, named `transactions/` nor `transactions/pair/`. Those two are for public fills (trades). The two corresponding methods are called **public**GetTransactionsPairs and **public**GetTransactions. Moreover, both of them are already implemented. 

If you want to implement fetchMyTrades, you should call privatePost**User**Transactions  (bitstamp v1 and v2) and privatePost**User**TransactionsPair (bitstamp v2) with corresponding params. 

Also, and this is very important, the private trade/transaction/fill is not the same as the order. For orders you should look at implementing the following endpoints:

```
// v1
                'open_orders',
                'order_status',
                'cancel_order',
                'cancel_all_orders',

```

```
// v2
                'open_orders/all/',
                'open_orders/{pair}',
                'order_status/',
                'cancel_order/',
```

And the corresponding methods are:

- fetchOpenOrders
- fetchOrders
- fetchClosedOrders
- fetchMyTrades

See how it's done in other exchanges as well. Does the above answer your question?

**Comment by jgordor** [comment]
Sure, thanks!
