### ISSUE TITLE
BTM is Bytom (HitBtc) and not Bitmark (Poloniex)

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#348]
Ahahah, coinmarketcap have both and one ticker for all :)

**Comment by kroitor** [comment]
Lol... What we gonna do? Any ideas? )

**Comment by kroitor** [comment]
![highlander](https://user-images.githubusercontent.com/1294454/31764449-e58efb50-b4c9-11e7-9633-94ef270a7859.jpg)

**Comment by mazertwo** [comment]
All what we have from Yobit, we need to add x (or more xxx :))))

**Comment by mazertwo** [comment]
Really shit exchange, hold CLAM on my balance. You can buy cryptocurrencies, but you cant withdraw. And you know about it only after buying...

**Comment by mazertwo** [comment]
may be add x, or more - xxx :))

**Comment by kroitor** [comment]
The one with higher market cap wins! ) Bytom remains BTM and Bitmark will be renamed BTM → Bitmark on Poloniex.
