### ISSUE TITLE
OHLCV for Poloniex

### ISSUE THREAD

**Issue by mondeja** [ccxt-dev/ccxt#349]
Bittrex in the V2 version [has this feature](https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=BTC-ETH&tickInterval=fiveMin), [here are](https://github.com/mondeja/bittrex_v2/blob/master/bittrex_v2/bittrex.py#L264) valid tickIntervals. In poloniex is the command `returnChartData`, you can see it in the [API documentation](https://poloniex.com/support/api/). I would include it but my PC run slow when I open 20000 lines of code in one file. I'll wait for the next version to contributing. Thanks for your work.

**Comment by kroitor** [comment]
@mondeja hi, sorry, but we actually already have OHLCV implemented for Bittrex based on their web data. Or did I miss somethign? As for the Poloniex - it is on the way.

**Comment by kroitor** [comment]
Good news: Poloniex has fetchOHLCV as of version 1.9.204+! Please update and feel free to ask your questions if you have difficulties using it. Should be straightforward from examples. Cheers!
