### ISSUE TITLE
Some other incompatible tickers with YoBit

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#350]
ICN is ICONOMI (kraken), not iCoin (yobit) - coinmarketcap have BOTH!!! as one ticker
AIR is AirToken (hitbtc, cmc), not AirCoin (yobit)
ANT is Aragon (hitbtc, cmc), not Ants Coin (yobit)
ATM is ATMChain (hitbtc, cmc), not Autumncoin (yobit)
DCT is Decent (hitbtc, cmc), not Discount (yobit)
DGD is DigixDAO (hitbtc, cmc), not DarkGoldCoin (yobit)
LUN is Lunyr (hitbtc, cmc), not LunarCoin (yobit)

**Comment by mazertwo** [comment]
All what we have from Yobit, we need to add x (or more xxx :))))

Really shit exchange, hold CLAM on my balance. With YoBit you can buy cryptocurrencies, but you cant withdraw. And you know about it only after buying... Криптогопота, короче :)

**Comment by kroitor** [comment]
@mazertwo ok, i'm going to bring them back to consistency with YoBit...
P.S. «Биткоины есть? А если найду?» %)
