### ISSUE TITLE
New exchange: Gate.io

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#353]
Can you add Gate.io exchange?
API here: https://gate.io/api2

**Comment by kroitor** [comment]
@mazertwo, looks like we can ;)

**Comment by mazertwo** [comment]
Bter recommend to withdraw all funds from them to gate.io with same login and pass. I think, gate.io is the new bter :)

**Comment by kroitor** [comment]
@mazertwo they do it all the time.. In fact it's so often, that I'm going to send them a suggestion to create an API for migrating the API next time...

**Comment by kroitor** [comment]
Done! ;)
