### ISSUE TITLE
Exchange logo on exchanges endpoint

### ISSUE THREAD

**Issue by AnujDutt2701** [ccxt-dev/ccxt#360]
Hi, as the title says, is it possible to include exchange logos into the response objects?

**Comment by kroitor** [comment]
Hi! Sorry, didn't quite understand what you mean... If "ex" is your exchange, than in most cases you can use `ex.urls['logo']`. This is a property of each exchange that is already available from the library and it is used to draw exchange logos on the main GitHub page of this project.
