### ISSUE TITLE
ccxt.php kuna throws exception

### ISSUE THREAD

**Issue by kiwina** [ccxt-dev/ccxt#361]
Declaration of ccxt\kuna::fetch_open_orders($symbol, $params = Array) 
should be compatible with ccxt\Exchange::fetch_open_orders($symbol = NULL, $params = Array)

**Comment by kroitor** [comment]
Hi! What's your version? Please update to the latest one. This issue was just fixed here: https://github.com/ccxt-dev/ccxt/issues/359. I'm closing this as a duplicate.
If still persists with the latest version for you, let us know. Thx!

**Comment by Mitrovic** [comment]
Hi,
I was updated to the latest version 1.10.181 and have same error.

**Comment by Mitrovic** [comment]
In the version 1.10.182 is same error:
 "message": "Declaration of ccxt\\kuna::fetch_my_trades($symbol) should be compatible with ccxt\\Exchange::fetch_my_trades($symbol = NULL, $since = NULL, $limit = NULL, $params = Array)",

**Comment by Mitrovic** [comment]
still the same 
"exception": "ErrorException: Declaration of ccxt\\kuna::fetch_my_trades($symbol, $since = NULL, $limit = NULL, $params = Array) should be compatible with ccxt\\Exchange::fetch_my_trades($symbol = NULL, $since = NULL, $limit = NULL, $params = Array) in ccxt/php/kuna.php:0\nStack trace:\n#0 /ccxt/ccxt.php(100):

**Comment by kroitor** [comment]
@Mitrovic sorry, for the inconvenience, I should've checked it myself, this new one coming up should clear it.

**Comment by kornrunner** [comment]
PHP version as well needs default `= NULL` for `$symbol` param

**Comment by Mitrovic** [comment]
Thank's @kornrunner

**Comment by kroitor** [comment]
@kornrunner that change gets propagated by the transpiler from JS to PHP, that method signature is now correct, at last. Thx!
