### ISSUE TITLE
New coin market (QTUM/KRW) and its API service has been launched in Bithumb exchange

### ISSUE THREAD

**Issue by dhmk815** [ccxt-dev/ccxt#366]
Hello, thank you for your fast reply.
This is another issue.
A few days ago, [bithumb exchage](https://www.bithumb.com/u1/US127) has opened new coin market, qtum/krw, and now its api service is available.
Could you add this market into both ccxt and ccxt.async in python?

**Comment by kroitor** [comment]
Sure!

**Comment by kroitor** [comment]
The QTUM/KRW was added to bithumb as of 1.9.224. Thx again!

**Comment by dhmk815** [comment]
Thank you @kroitor . You are the best.
