### ISSUE TITLE
How to enable sandbox?

### ISSUE THREAD

**Issue by luigikitten** [ccxt-dev/ccxt#369]
Hi,
  newbie here :) How can I force the usage of the exchange sandbox? I would like to test a bit before trading with real cryptomoney..

Thanks!
Luigi

**Comment by kroitor** [comment]
Hi, Luigi!

Most often you should just change the url of the exchange to sandbox url, like shown in the example bellow:

```
    // move to testnet/sandbox if possible
    if (exchange.urls['test'])
        exchange.urls['api'] = exchange.urls['test'];
```

The caveat here is that the test URLs are not fully covered in ccxt yet, so you will have to put correct URLs there. But if you feel like you want to help us to unify that functionality and you want contribute by adding the test URLs where they are missing – we will be happy for your help. Let us know if this answers your question.

**Comment by luigikitten** [comment]
Thanks! I will try

**Comment by kroitor** [comment]
I'm closing this for now, let us know if you have difficulties with it, feel free to reopen this if needed, or just ask your questions! Cheers!
