### ISSUE TITLE
bitfinex or bitfinex2?

### ISSUE THREAD

**Issue by aking7** [ccxt-dev/ccxt#371]
Hi, I'm trying to add the Bitfinex `price_precision` endpoint into the fetch_markets() method but I'm a bit confused about the `bitfinex` vs `bitfinex2` classes.

It appears `bitfinex2` inherits the methods from `bitfinex`, so I wanted to add the `price_precision` endpoint to `bitfinex`, but it gets overridden by `markets` in `bitfinex2`. Is there a reason why `markets` are hard coded for `bitfinex2`?

Great package by the way :)

**Comment by kroitor** [comment]
Hi, @aking7!

> It appears bitfinex2 inherits the methods from bitfinex, so I wanted to add the price_precision endpoint to bitfinex, but it gets overridden by markets in bitfinex2.

Yep, that's how it is.

> Is there a reason why markets are hard coded for bitfinex2?

Sure! The Bitfinex v2 API is still a beta-version, and they don't have a REST endpoint for fetching a list of all markets from v2, therefore we had to hardcode them for now, but we are thinking of actually falling back to v1 for fetchMarkets method in our v2 implementation. You can do it yourself, we will be happy if you submit a PR, take a look how bitstamp and hitbtc endpoints fall back to other versions, for reference. Also read the CONTRIBUTING doc in the root of this repository, if you decide to give it a try. 

I'd close this issue for now if you don't mind. Feel free to reopen it, or ask your questions, if you have any. Thx!

**Comment by aking7** [comment]
Ah I see. I'll look into it if I find some time :)

**Comment by kroitor** [comment]
@aking7 that would be awesome! But don't bother if you're occupied, we will do it anyway, hopefully very soon (it usually takes less than few days).

**Comment by aking7** [comment]
@kroitor I tried to run `node run-tests --js` for my implementation in `bitfinex` but am getting an error.
```
[DIR]\ccxt\run-tests.js:116
const sequentialMap = async (input, fn) => {
                            ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```
I'm kind of new to this so maybe I'm missing something.

**Comment by kroitor** [comment]
What's your node version? You need to update your node version to 7.6+ to run the tests.

**Comment by aking7** [comment]
Ah my bad! I just downloaded but grabbed the wrong version.

**Comment by aking7** [comment]
@kroitor I'm getting closer but now I have this error for `npm run build`:
```
Preparing for PyPI → README.rst (pipez.js:23)
DIR\ccxt\update-badges.js:24
let rstExchangeTableLines = match[2].split ("\n")
                                 ^

TypeError: Cannot read property '2' of null
    at Object.<anonymous> (DIR\ccxt\update-badges.js:24:34)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
Am I missing some node module? Hopefully I can contribute more if I get this sorted :)

**Comment by kroitor** [comment]
Are there any other messages in your output besides before the one you posted?

> Hopefully I can contribute more if I get this sorted :)

We will get through it ;)

**Comment by aking7** [comment]
```
> ccxt@1.9.228 build DIR\ccxt
> npm run export-exchanges && npm run vss && npm run mdrst && npm run transpile && npm run update-badges && npm run browserify


> ccxt@1.9.228 export-exchanges DIR\ccxt
> node export-exchanges

Exporting exchanges → ./ccxt.js (pipez.js:23)
Exporting exchanges → ./ccxt/exchanges.py (pipez.js:23)
Exporting exchanges → ./ccxt.php (pipez.js:23)
Base sources updated successfully. (pipez.js:23)
Exporting exchanges to README.md ... (pipez.js:23)
Exporting exchanges to ccxt.wiki/Exchange-Markets.md ... (pipez.js:23)
Exporting exchanges to ccxt.wiki/Manual.md ... (pipez.js:23)
Exporting exchange ids to exchanges.json (pipez.js:23)
Exchanges exported successfully. (pipez.js:23)

> ccxt@1.9.228 vss DIR\ccxt
> node vss

Old version:  1.9.228 (pipez.js:23)
New version:  1.9.228 (pipez.js:23)
Single-sourcing version 1.9.228 ./package.json → ./ccxt.js (pipez.js:23)
Single-sourcing version 1.9.228 ./package.json → ./ccxt/version.py (pipez.js:23)
Single-sourcing version 1.9.228 ./package.json → ./ccxt.php (pipez.js:23)
Version single-sourced successfully. (pipez.js:23)

> ccxt@1.9.228 mdrst DIR\ccxt
> pandoc --wrap=preserve --columns=10000 --from=markdown --to=rst --output=README.rst README.md


> ccxt@1.9.228 transpile DIR\ccxt
> node transpile

Transpiling ./ccxt/exchanges.py → ./ccxt/exchanges.py (pipez.js:23)
Transpiling ./ccxt/async/exchanges.py → ./ccxt/async/exchanges.py (pipez.js:23)
Transpiling ./ccxt.php → ./build/ccxt.php (pipez.js:23)
Transpiling ./test/test_async.py → ./test/test.py (pipez.js:23)
Transpiled successfully. (pipez.js:23)

> ccxt@1.9.228 update-badges DIR\ccxt
> node update-badges

Preparing for PyPI → README.rst (pipez.js:23)
DIR\ccxt\update-badges.js:24
let rstExchangeTableLines = match[2].split ("\n")
                                 ^

TypeError: Cannot read property '2' of null
    at Object.<anonymous> (DIR\ccxt\update-badges.js:24:34)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.9.228 update-badges: `node update-badges`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ccxt@1.9.228 update-badges script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     DIR\AppData\Roaming\npm-cache\_logs\2017-10-22T18_06_15_834Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.9.228 build: `npm run export-exchanges && npm run vss && npm run mdrst && npm run transpile && npm run update-badges && npm run browserify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ccxt@1.9.228 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     DIR\AppData\Roaming\npm-cache\_logs\2017-10-22T18_06_15_919Z-debug.log
```
Let me know if you need the log files but I didn't see anything of interest in them.

**Comment by kroitor** [comment]
Can you please upload the README.rst that was generated by the build scripts somewhere? A gist will do, thx! Also, please do the following: `pandoc -v` in your command line... which version is it?

**Comment by aking7** [comment]
`pandoc 1.19.2.1`

[https://gist.github.com/aking7/3828acb7dc380f0898d4d236f632800f](url)

**Comment by aking7** [comment]
Okay, I don't know why the link doesn't work...

**Comment by kroitor** [comment]
@aking7 no problem, I got it: https://gist.githubusercontent.com/aking7/3828acb7dc380f0898d4d236f632800f/raw/d26e04cb2a2143c90077a0179afab8f8276bcab3/README.rst

**Comment by kroitor** [comment]
@aking7 that's strange, when I do it on my side with your file, the update-badges.js script works smoothly... Did you do any edits to the sources or files in the repo before running npm run build?

**Comment by kroitor** [comment]
Oh, I think I got it. You should run npm build from inside DIR where ccxt is :)

**Comment by aking7** [comment]
Nope, no edits. And I'm in my ccxt DIR. The transpiling is successful, it's just when preparing for PyPI.

**Comment by kroitor** [comment]
@aking7 well, you can skip it anyway because it doesn't do anything except updating the exchange count in the docs, so... It does not affect the build. You actually have it built now. So you can run npm run tests and go on with your plan.

**Comment by kroitor** [comment]
@aking7 btw, can you please show file permissions inside DIR ? Do `ls -alh` please. Thx!

**Comment by aking7** [comment]
I'm on Windows but `DIR\ccxt>dir /a` gives me:
```
 Volume in drive C is Windows
 Volume Serial Number is EC3A-B103

 Directory of DIR\ccxt

22-Oct-17  21:13    <DIR>          .
22-Oct-17  21:13    <DIR>          ..
14-Oct-17  17:47               124 .eslintrc
22-Oct-17  21:22    <DIR>          .git
14-Oct-17  17:47               465 .gitattributes
14-Oct-17  17:47               551 .gitignore
14-Oct-17  17:47               260 .npmignore
19-Oct-17  14:45             3,891 .travis.yml
22-Oct-17  20:59    <DIR>          build
22-Oct-17  21:04    <DIR>          ccxt
14-Oct-17  17:47               195 ccxt.browser.js
17-Oct-17  02:45    <DIR>          ccxt.egg-info
22-Oct-17  21:20           827,513 ccxt.js
22-Oct-17  21:09            48,221 ccxt.php
22-Oct-17  19:25    <DIR>          ccxt.wiki
22-Oct-17  17:12            27,230 CHANGELOG.md
14-Oct-17  17:47            14,235 CONTRIBUTING.md
14-Oct-17  17:47             5,827 countries.js
19-Oct-17  14:45    <DIR>          doc
14-Oct-17  17:47               542 example.js
22-Oct-17  17:12    <DIR>          examples
22-Oct-17  21:09             1,736 exchanges.json
14-Oct-17  17:47             7,891 export-exchanges.js
22-Oct-17  17:12             7,795 keys.json
14-Oct-17  17:47             1,090 LICENSE.txt
14-Oct-17  17:47               104 MANIFEST.in
22-Oct-17  19:59    <DIR>          node_modules
22-Oct-17  19:59             6,287 package-lock.json
22-Oct-17  21:04             5,205 package.json
14-Oct-17  17:47               297 push-wiki.sh
14-Oct-17  17:47               529 push.sh
22-Oct-17  21:09            44,494 README.md
22-Oct-17  21:09            73,573 README.rst
19-Oct-17  14:45             9,727 run-tests.js
14-Oct-17  17:47               602 setup.cfg
14-Oct-17  17:47             2,121 setup.py
22-Oct-17  21:04    <DIR>          test
14-Oct-17  17:47               385 tox.ini
22-Oct-17  17:12            26,762 transpile.js
14-Oct-17  17:47             2,036 update-badges.js
14-Oct-17  17:47             2,637 vss.js
              30 File(s)      1,122,325 bytes
              11 Dir(s)  40,153,346,048 bytes free
```

**Comment by kroitor** [comment]
@aking7 just a sec, I'll upload a quickfix for the update-badges.js script and we'll try again to make it run without a problem. Will get back to you in a couple of minutes.

**Comment by aking7** [comment]
Also `node run-tests --js` is fine except for some Exchange Not Available and Request Timeout warnings, but running `node run-tests` gives:
```
Testing { exchanges: <array[91]>, symbol: "all", keys: { '--js': false, '--php': false, '--python': false, '--python3': false } } (pipez.js:23)
[Error] spawn python2 ENOENT

    at _errnoException        util.js:1021
    at onexit                 internal/child_process.js:192
    at onErrorNT              internal/child_process.js:374
    at _combinedTickCallback  internal/process/next_tick.js:138
    at _tickCallback          internal/process/next_tick.js:180   (pipez.js:23)
```
I have both Python 2 and 3 as far as I can tell. Thanks for all the help!

**Comment by kroitor** [comment]
@aking7 

> I have both Python 2 and 3 as far as I can tell.

Yes, your setup is fine, it's just that we had to put python2 to launch the version 2 on Travis. You can run node run-tests --python3 (it's the same as with python2). We will also fix for that as well, thx for pointing that out.

Can you please update the repo with `git pull` and try `npm run build` again?

**Comment by aking7** [comment]
@kroitor Still getting the same error :/

**Comment by aking7** [comment]
@kroitor I've also noticed that during the build the `build\ccxt.php` file gets some of the `)` changed to `}` improperly. I need to call it a night, but I will make a pull request of my changes for you to try. It's just a couple lines for the `price_precision` in `bitfinex` so I imagine it will work fine on your end.

**Comment by kroitor** [comment]
@aking7 I'm going to debug the build further to find the reason and to make it build on windows. Will get back to you hopefully soon! Thx for the PR!
