### ISSUE TITLE
Different OHLC Result from exchanges

### ISSUE THREAD

**Issue by ralondo** [ccxt-dev/ccxt#382]
The fetch_ohlcv delivers different data for different exchanges. I tried it with kraken and bitfinex V2.
From kraken I get:
timestamp,open,high,low,close,volume
and from bitfinex:
timestamp,open,close,high,low,volume

I think it would be better if this would be always the same no matter which exchange, e.g. timestamp,open,high,low,close,volume.

Is this a bug or do you "just" deliver the data as it comes from those exchanges? If the later then it would be right but would be confusing and should be noted so in the docs.

Thanks for correction - and your really awesome work!

**Comment by kroitor** [comment]
Hi, @ralondo ! What's your version of ccxt? This issue has been addresses here: https://github.com/ccxt-dev/ccxt/issues/374 and it was fixed yesterday. Can you verify that you are still getting inconsistent data with the most up to date version of the library?

**Comment by ralondo** [comment]
OK, got me ;) I'm still using the version I downloaded yesterday morning. I'll get the newest one and will report back.

**Comment by kroitor** [comment]
@ralondo yeah, as you may know, we are still under heavy development, so, fixes and edits are added daily. Therefore we ask our users to update frequently until we settle it fully unified. We will be happy if you report back if it works for you or not. Thx!

**Comment by kroitor** [comment]
@ralondo BTW, as of yesterday you can now fetch OHLCV with bitfinex v1 as well ;)

**Comment by ralondo** [comment]
OK, looks good! Guys, you're doing a fantastic job here, absolutly stunning work! Exactly the kind of exchange interface wrapper I need at the moment. Already started to write my own until I saw this here yesterday.
From now on I will daily check for updates.
