### ISSUE TITLE
Bitstamp fetch_trades returns wrong timestamp

### ISSUE THREAD

**Issue by ralondo** [ccxt-dev/ccxt#384]
As the title says, the returned timestamp I get from bitstamp V2 fetch_trades is wrong. According to your docs it should always be milliseconds (like it is for example with bitfinex) but it returns seconds. I know bitstamp API returns seconds and not milliseconds so please let your wrapper correct this.

Thanks for the fix!

**Comment by kroitor** [comment]
This should be fixed as of version 1.9.241+. Let us know if you still have any difficulties with it. Thx!

**Comment by ralondo** [comment]
Works like charm, thanks!
