### ISSUE TITLE
Warning loading tickers from kuna

### ISSUE THREAD

**Issue by rubobaquero** [ccxt-dev/ccxt#386]
```
$exchange = new \ccxt\kuna();
$exchange->load_markets();
$exchange->fetch_tickers($exchange->symbols);
```

publicGetTickers not foundPHP Warning:  array_keys() expects parameter 1 to be array, null given in /Applications/XAMPP/xamppfiles/htdocs/cryptosignals/ccxt.php on line 2009

Thanks in advance!

**Comment by kroitor** [comment]
@rubobaquero, but Kuna doesn't have this endpoint, if you `var_dump($exchange->hasFetchTickers);` property, you'll see it's false. No `fetch_tickers()` method for Kuna. You can only fetch single tickers per pair with `fetchTicker()`. Does this answer your question?

**Comment by kroitor** [comment]
@rubobaquero current overview (work in progress):

<img width="1572" alt="screen shot 2017-10-24 at 14 44 07" src="https://user-images.githubusercontent.com/1294454/31941246-d8d05ac2-b8c9-11e7-89c3-5234012f8425.png">
