### ISSUE TITLE
Enhancement: Add cryptowat.ch

### ISSUE THREAD

**Issue by ralondo** [ccxt-dev/ccxt#387]
Could you add cryptowat.ch? It's not an exchange by itself but it has an API to get some data that some exchanges are missing like 3m OHLC data and more. It's a nice fallback if an exchange isn't working.

**Comment by kroitor** [comment]
@ralondo I'll take a look into it as soon as I get through urgent issues. Thx for your proposal. Unfortunately, we had trouble unifying aggregators previously (very specific APIs), so we are trying to be careful and to not promise that right away. Thx for your understanding. I'll let you know on the progress of this issue, closing it for now.
