### ISSUE TITLE
Kraken fetch_my_trades 50 entries limit

### ISSUE THREAD

**Issue by D-Code** [ccxt-dev/ccxt#391]
It seems not possible to get more than 50 entries from fetch_my_trades. Is there a way to specify a limit higher than 50 entries?

Here is some example code and output:
```
print('ccxt version', ccxt.__version__)
# Output: ccxt version 1.9.244

def setup_kraken():
    """Setup Kraken with API keys"""
    xchng = ccxt.kraken({'apiKey': '<apiKey>', 'secret': '<secret>'})
    return xchng


kraken = setup_kraken()
trades_history = kraken.fetch_my_trades()
print('fetch_my_trades', 'length', len(trades_history))
# Output: fetch_my_trades length 50
trades_history = kraken.private_post_tradeshistory()
print('private_post_tradeshistory', 'result trades length', len(trades_history['result']['trades']))
# Output: private_post_tradeshistory result trades length 50
print('private_post_tradeshistory', 'result count', trades_history['result']['count'])
# Output: private_post_tradeshistory result count 81
```

One interesting thing is the count value from private_post_tradeshistory, which is the exact number of trades that is specified when logging in to Kraken and navigating to History->Trades.

If it's not possible to specify the limit via parameter or something, then I guess one has to do a manual export of trades history from the exchange website - this notion was also mentioned here: https://github.com/ccxt-dev/ccxt/issues/129#issuecomment-323607694

(Edit: added ccxt version.)

**Comment by kroitor** [comment]
Hi, D-Code!

Ready? Here you go:

```
def setup_kraken():
    """Setup Kraken with API keys"""
    xchng = ccxt.kraken({
        'apiKey': '<apiKey>',
        'secret': '<secret>',
        'enableRateLimit': True, # add time.sleep or enableRateLimit to avoid ban and nonce trouble
    })
    return xchng


kraken = setup_kraken()
batch_size = 50
for i in range(0,1000,50):
    trades_history = kraken.fetch_my_trades(None, {'ofs':i}) # added an extra offset param here
    print('fetch_my_trades', 'length', len(trades_history))
```

The count is the total count of trades, but the max output is 50. Does this help?

**Comment by D-Code** [comment]
Yes! Looks really good! :-D
Thank you for your swift and accurate response! Closing this. :-)
