### ISSUE TITLE
EMERGENCY: code error in V 1.9.258

### ISSUE THREAD

**Issue by ralondo** [ccxt-dev/ccxt#397]
Your forgot a closing ";" in your code, on line 10261

**Comment by kroitor** [comment]
Thx for reporting, and my apologies for the inconvenience. It slipped through the tests, we'll add more checks for that. The fixed new version will arrive in 5 minutes. Thx once again!

**Comment by kroitor** [comment]
Fixed in 1.9.259+. Thx a lot!
