### ISSUE TITLE
New exchange EtherDelta

### ISSUE THREAD

**Issue by guopengliang** [ccxt-dev/ccxt#404]
There's an emerging exchange called EtherDelta. API available here:
https://github.com/etherdelta/etherdelta.github.io/blob/master/docs/API.md
https://etherdelta.com

It would be awesome if we could support this exchange.
Thanks!

**Comment by kroitor** [comment]
Currently, it's a websocket-only API, no REST, so we are going to implement it later this autumn, when we announce WS support (it is in on the way now). Therefore I'm closing this for now, but we will update you on this further down the road. Thx!
