### ISSUE TITLE
GDAX returns strings  => cast to float

### ISSUE THREAD

**Issue by stefandeml** [ccxt-dev/ccxt#405]
Using with GDAX results in the following error: `"must be real number, not str`
Need to cast string to float to make math operations work      

```
       precision = {
-                'amount': -math.log10(amountLimits['min']),
-                'price': -math.log10(priceLimits['min']),
+                'amount': -math.log10(float(amountLimits['min'])),
+                'price': -math.log10(float(priceLimits['min'])),
}

```

**Comment by kroitor** [comment]
Oh, ok... I'll fix it right away!

![fix](https://user-images.githubusercontent.com/1294454/32059679-844fda74-ba75-11e7-84fd-9e5d4490aa64.jpg)

**Comment by stefandeml** [comment]
thanks a ton.
any chance for the future to create a fix myself? (enable branches on the repo?)

**Comment by kroitor** [comment]
@stefandeml you're welcome!  If you feel like you want to contribute then go ahead, plz, feel free to submit PRs like other people do ;) No time for branches :)) Just make sure to read the [CONTRIBUTING](https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md) doc before actually making the changes. Also, so you can see from the edits introduced by the above commit, it's a pretty straightforward fix, and it maps one-to-one to your initial post, that gets inherited (transpiled) in Py from JS (more on that in the contributing doc).
