### ISSUE TITLE
New exchange Coinsbank

### ISSUE THREAD

**Issue by guopengliang** [ccxt-dev/ccxt#407]
Hi, please add support to the UK-based exchange [Coinsbank](https://coinsbank.com):
https://github.com/coinsbank/coinsbank-php-sdk

**Comment by kroitor** [comment]
Hi! Unfortunately, they don't have a normal exchange API, namely, no orderbooks endpoint, no tickers endpoint, no trades... And no docs... Sorry for that, but I don't think we can integrate them until they offer at least a decent set of methods + docs (I can't even find anything about the API on their website, except that GitHub link to their merchant API in PHP, which isn't an exchange API at all).

**Comment by guopengliang** [comment]
Oooops, I guess we have to wait until they have better API docs and supports. Thanks!
